begin;

-- Diong Connections (V1, Phase A): schema, ownership integrity and RLS only.
-- No RPCs, routes or UI are introduced here. Interactions are append-only in V1.

create table public.connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  connection_type text not null,
  connection_purpose text not null,
  why_it_matters text,
  preferred_contact_days integer,
  last_meaningful_contact_at timestamptz,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint connections_name_length
    check (char_length(btrim(name)) between 1 and 120),
  constraint connections_type_allowed check (connection_type in (
    'friend',
    'family',
    'mentor',
    'accountability_partner',
    'colleague',
    'professional_contact',
    'collaborator',
    'study_partner',
    'community',
    'coach_adviser',
    'other'
  )),
  constraint connections_purpose_allowed check (connection_purpose in (
    'career_growth',
    'accountability',
    'learning',
    'friendship',
    'family',
    'collaboration',
    'networking',
    'support',
    'shared_goal',
    'community',
    'personal_growth',
    'other'
  )),
  constraint connections_why_it_matters_length
    check (why_it_matters is null or char_length(why_it_matters) <= 500),
  constraint connections_notes_length
    check (notes is null or char_length(notes) <= 2000),
  constraint connections_preferred_contact_days_range
    check (preferred_contact_days is null or preferred_contact_days between 1 and 365),
  -- Target for the composite foreign key from connection_interactions. This
  -- guarantees an interaction can only ever reference a connection owned by the
  -- same user, enforced by the database rather than application code alone.
  constraint connections_id_user_id_key unique (id, user_id)
);

create table public.connection_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  connection_id bigint not null,
  interaction_type text not null,
  occurred_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  constraint connection_interactions_type_allowed check (interaction_type in (
    'message',
    'call',
    'video',
    'in_person',
    'email',
    'other'
  )),
  constraint connection_interactions_notes_length
    check (notes is null or char_length(notes) <= 2000),
  constraint connection_interactions_connection_fk
    foreign key (connection_id, user_id)
    references public.connections (id, user_id) on delete cascade
);

create index connections_user_active_idx
  on public.connections (user_id, is_active);
create index connections_user_last_contact_idx
  on public.connections (user_id, last_meaningful_contact_at)
  where is_active;
create index connection_interactions_connection_idx
  on public.connection_interactions (connection_id, occurred_at desc);
create index connection_interactions_user_id_idx
  on public.connection_interactions (user_id);

create trigger connections_set_updated_at
before update on public.connections
for each row execute function public.set_updated_at();

alter table public.connections enable row level security;
alter table public.connection_interactions enable row level security;

revoke all on public.connections from anon, authenticated;
revoke all on public.connection_interactions from anon, authenticated;

-- connections: owner CRUD with column-scoped INSERT and UPDATE. Clients never
-- write id, created_at or updated_at (defaults/trigger own them) and never write
-- user_id after creation, so ownership cannot be reassigned.
-- last_meaningful_contact_at is system-managed: it is intentionally excluded
-- from both grants and will be maintained only by the Phase B
-- record_connection_interaction() SECURITY DEFINER RPC.
grant select, delete on public.connections to authenticated;
grant insert (
  user_id,
  name,
  connection_type,
  connection_purpose,
  why_it_matters,
  preferred_contact_days,
  notes,
  is_active
) on public.connections to authenticated;
grant update (
  name,
  connection_type,
  connection_purpose,
  why_it_matters,
  preferred_contact_days,
  notes,
  is_active
) on public.connections to authenticated;

-- connection_interactions: append-only and RPC-only in V1. Owners may read their
-- own rows. There is no direct INSERT/UPDATE/DELETE grant or policy; Phase B adds
-- record_connection_interaction() as a SECURITY DEFINER RPC that verifies
-- ownership, validates occurred_at, inserts the interaction and updates
-- connections.last_meaningful_contact_at atomically.
grant select on public.connection_interactions to authenticated;

create policy "Users can read their own connections"
on public.connections for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own connections"
on public.connections for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own connections"
on public.connections for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own connections"
on public.connections for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their own connection interactions"
on public.connection_interactions for select
to authenticated
using ((select auth.uid()) = user_id);

-- No INSERT/UPDATE/DELETE policy on connection_interactions in Phase A. Writes
-- arrive only through the Phase B record_connection_interaction() RPC.

commit;
