begin;

-- Diong Action & Focus — Pass 9 Step 1: Daily Direction.
--
-- Additive only. Adds one table (public.daily_directions), its indexes, RLS
-- and two triggers. Nothing in this file alters an existing table, function,
-- grant, policy or trigger. Daily Prime, the social graph, posts/feed,
-- notifications, Discover/Search, direct messages, communities, Goals,
-- Habits and the Journal are untouched.
--
-- Apply once, in order, after 202609140001_search_and_profile_read_performance.sql.
-- Depends on public.profiles / auth.users (202607190001), public.goals and
-- public.habits (202609130001) for Daily Direction's optional cross-links,
-- and public.set_updated_at() (202607190001). Each migration is a single
-- transaction and is NOT idempotent — never re-run a migration that already
-- succeeded.
--
-- Privacy: strictly owner-only. There is no shared, public or cross-user
-- select policy anywhere in this file. Daily Direction is never surfaced by
-- the feed, Discover, Search, public profiles, communities, messages, or
-- notifications sent to other users — same guarantee as goals/habits/
-- journal_entries in the previous pass.
--
-- Architecture decision: a Daily Direction is user-authored, top-level,
-- single-owner content with no child/derived table beneath it (unlike
-- goal_milestones / habit_checkins) — so it follows the plain owner-CRUD,
-- column-scoped-grant model public.goals already uses, not an RPC-only
-- model. No new RPC is introduced in this migration. `direction_date` is
-- deliberately NOT part of any grant (it can only ever take its column
-- default, `current_date`, at insert, and never changes after) — the app
-- only ever writes "today's" direction, there is no backdating UI, and this
-- keeps the one-row-per-day rule simple to reason about at the database
-- layer. `status` transitions (active -> completed / skipped, or back to
-- active) are a plain column UPDATE, exactly mirroring how public.goals
-- handles `status` — completed_at is derived by a BEFORE UPDATE trigger,
-- the same apply_goal_completion_status() pattern, so a client can never
-- forge it.
--
-- Date-safety note (see docs/DAILY_DIRECTION.md for the full writeup):
-- `direction_date` defaults to `current_date`, which resolves in the
-- database session's timezone (UTC), matching every other calendar-day
-- concept already in Diong (public.prime_assignments.assigned_date,
-- public.habit_checkins.checkin_date, public.journal_entries.entry_date).
-- This is a deliberate, consistent choice, not an oversight: introducing a
-- different (e.g. client-local) day boundary for only this one table would
-- make Diong's "today" mean two different things depending on which
-- feature a user is looking at, which is worse than a single, well-
-- documented limitation. The known limitation — a user active close to
-- their local midnight, in a timezone far from UTC, can see "today" flip a
-- number of hours before or after their own local midnight — is unchanged
-- from the existing, already-shipped behaviour and is tracked as one item
-- (not four) in docs/RELEASE_CHECKLIST.md's "Known deferred" section.
-- Proper per-user timezone support is a larger, cross-feature change and is
-- out of scope for this step.

create table public.daily_directions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  direction_date date not null default current_date,
  intention text,
  desired_identity text,
  primary_action text not null,
  why_it_matters text,
  goal_id bigint references public.goals(id) on delete set null,
  habit_id bigint references public.habits(id) on delete set null,
  status text not null default 'active',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_directions_user_date_key unique (user_id, direction_date),
  -- The one required field: "the most meaningful action you need to take
  -- today" is enough on its own for the record to be useful, matching the
  -- brief's "at minimum, the primary intention/action must provide enough
  -- meaning" requirement without forcing all four prompts on the user.
  constraint daily_directions_primary_action_length
    check (char_length(btrim(primary_action)) between 1 and 240),
  constraint daily_directions_intention_length
    check (intention is null or char_length(btrim(intention)) between 1 and 280),
  constraint daily_directions_desired_identity_length
    check (desired_identity is null or char_length(btrim(desired_identity)) between 1 and 160),
  constraint daily_directions_why_it_matters_length
    check (why_it_matters is null or char_length(btrim(why_it_matters)) between 1 and 1000),
  constraint daily_directions_status_allowed
    check (status in ('active', 'completed', 'skipped'))
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- daily_directions_user_date_key (above) already indexes (user_id,
-- direction_date) ascending and is what "today's direction" and the
-- one-per-day rule rely on. No separate descending index is added: unlike
-- habit_checkins (whose unique constraint is keyed on (habit_id,
-- checkin_date), a different leading column from the (user_id,
-- checkin_date desc) read index it also carries), this table's unique
-- constraint's leading columns already exactly match the bounded "recent
-- directions" read's filter + sort (`where user_id = ? order by
-- direction_date desc limit ?`), so Postgres can satisfy it with a
-- backward scan of the ascending unique index directly. A second index
-- would be redundant here.

-- ---------------------------------------------------------------------------
-- Triggers: system-managed derived columns
-- ---------------------------------------------------------------------------

create trigger daily_directions_set_updated_at
before update on public.daily_directions
for each row execute function public.set_updated_at();

-- Keeps completed_at consistent with a status change in the same statement:
-- entering 'completed' stamps completed_at; leaving 'completed' (back to
-- 'active', or — not expected in practice, but handled the same way — to
-- 'skipped') clears it. Mirrors apply_goal_completion_status() exactly,
-- minus the progress_percent side effect goals has and Daily Direction does
-- not.
create function public.apply_direction_completion_status()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' then
    new.completed_at := now();
  elsif new.status <> 'completed' and old.status = 'completed' then
    new.completed_at := null;
  end if;
  return new;
end;
$$;

create trigger daily_directions_apply_completion_status
before update on public.daily_directions
for each row execute function public.apply_direction_completion_status();

-- Same-owner integrity for the two optional cross-links, mirroring
-- enforce_journal_entry_ownership() exactly (security definer so the
-- existence checks are not themselves subject to goals/habits RLS from
-- inside the trigger — the check is against new.user_id either way, so this
-- only ever confirms what RLS would already imply, never widens what a
-- caller can see).
create function public.enforce_daily_direction_ownership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.goal_id is not null and not exists (
    select 1 from public.goals where id = new.goal_id and user_id = new.user_id
  ) then
    raise exception using errcode = '42501', message = 'That goal is not available.';
  end if;

  if new.habit_id is not null and not exists (
    select 1 from public.habits where id = new.habit_id and user_id = new.user_id
  ) then
    raise exception using errcode = '42501', message = 'That habit is not available.';
  end if;

  return new;
end;
$$;

create trigger daily_directions_enforce_ownership
before insert or update on public.daily_directions
for each row execute function public.enforce_daily_direction_ownership();

revoke all on function public.apply_direction_completion_status() from public, anon, authenticated;
revoke all on function public.enforce_daily_direction_ownership() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.daily_directions enable row level security;

revoke all on public.daily_directions from anon, authenticated;

-- Owner CRUD, column-scoped INSERT/UPDATE, no DELETE grant at all — a
-- direction is marked 'skipped', never hard-deleted, matching goals/habits.
-- direction_date is never in either grant (default-only, immutable after
-- creation); id, created_at, updated_at and completed_at are never
-- client-writable.
grant select on public.daily_directions to authenticated;
grant insert (
  user_id, intention, desired_identity, primary_action, why_it_matters,
  goal_id, habit_id
) on public.daily_directions to authenticated;
grant update (
  intention, desired_identity, primary_action, why_it_matters,
  goal_id, habit_id, status
) on public.daily_directions to authenticated;

create policy "Users can read their own daily directions"
on public.daily_directions for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own daily directions"
on public.daily_directions for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- Past directions are read-only: an update is only permitted while
-- direction_date still equals current_date (the same UTC "today" the
-- column's default already resolves to). Once the calendar day rolls
-- over, the row can still be selected but no longer updated — matching
-- the "today's direction can be edited; recent/past directions are
-- read-only" rule documented in docs/DAILY_DIRECTION.md.
create policy "Users can update their own daily directions"
on public.daily_directions for update
to authenticated
using ((select auth.uid()) = user_id and direction_date = current_date)
with check ((select auth.uid()) = user_id and direction_date = current_date);

commit;
