begin;

-- Diong Notifications, Discover & Search — Social Network Pass 3.
--
-- Additive only. Adds one table (public.notifications), its RLS and four
-- SECURITY DEFINER RPCs; three new AFTER INSERT triggers on the
-- already-shipped public.follows / public.post_likes / public.post_comments
-- tables that generate notifications from the existing follow_user() /
-- like_post() / create_comment() write paths (no new client-writable
-- surface); and four read-only SECURITY DEFINER RPCs for Discover and Search.
-- Nothing in this file alters an existing table, function, grant, policy or
-- trigger. Daily Prime, Prime history / reflections, Connections, the Pass 1
-- follow / block graph and the Pass 2 post / comment / like / bookmark
-- semantics are untouched.
--
-- Apply once, in order, after 202609100003_social_content.sql. Each migration
-- is a single transaction and is NOT idempotent — never re-run a migration
-- that already succeeded.

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  notification_type text not null,
  entity_type text,
  entity_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint notifications_type_allowed check (notification_type in (
    'new_follower',
    'post_like',
    'post_comment',
    'comment_reply'
  )),
  constraint notifications_entity_type_allowed check (
    entity_type is null or entity_type in ('profile', 'post', 'comment')
  ),
  -- The recipient never receives a notification about their own action. This
  -- is defence in depth — every trigger below already skips self-actions —
  -- kept true regardless of how a row is inserted.
  constraint notifications_actor_not_recipient check (
    actor_user_id is null or actor_user_id <> user_id
  ),
  -- Ties each notification_type to its exact (entity_type, entity_id
  -- nullability) shape, so a malformed row can never be inserted by any code
  -- path. entity_id is intentionally NOT foreign-keyed: it is polymorphic
  -- (a post id or a comment id depending on type) and Postgres has no
  -- conditional FK. Staleness (the post/comment later soft-deleted) is
  -- handled by list_notifications(), not by cascade — see docs.
  constraint notifications_type_entity_consistent check (
    (notification_type = 'new_follower'
      and entity_type = 'profile' and entity_id is null)
    or (notification_type = 'post_like'
      and entity_type = 'post' and entity_id is not null)
    or (notification_type = 'post_comment'
      and entity_type = 'post' and entity_id is not null)
    or (notification_type = 'comment_reply'
      and entity_type = 'comment' and entity_id is not null)
  )
);

create index notifications_user_created_idx
  on public.notifications (user_id, created_at desc);
create index notifications_user_read_created_idx
  on public.notifications (user_id, read_at, created_at desc);
create index notifications_actor_user_id_idx
  on public.notifications (actor_user_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.notifications enable row level security;

revoke all on public.notifications from anon, authenticated;

-- Reads only. Every write (creation, read-state) goes through a trigger or a
-- SECURITY DEFINER RPC below, matching the Pass 1 / Pass 2 RPC-only model.
grant select on public.notifications to authenticated;

create policy "Users can read their own notifications"
on public.notifications for select
to authenticated
using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------------------
-- Notification creation — triggers on the existing Pass 1 / Pass 2 tables
-- ---------------------------------------------------------------------------
-- These attach to public.follows / public.post_likes / public.post_comments,
-- which already exist from earlier passes. This is additive DDL against
-- those tables, not a modification of the migrations that created them —
-- the only write paths that reach these tables (follow_user(), like_post(),
-- create_comment()) are unchanged, so there is still no way for a browser to
-- insert an arbitrary notification row.
--
-- Documented dedup policy: a like/unlike/re-like cycle, or a
-- follow/unfollow/re-follow cycle, notifies the recipient ONCE — the first
-- time that actor produces that relationship with that target. This is
-- deterministic and needs no time-window heuristic, and matches "prefer no
-- uncontrolled notification spam." A later re-like or re-follow between the
-- same two accounts does not create a second notification. Comments and
-- replies are not deduplicated — each is a distinct real event, not a
-- repeatable toggle.

create function public.notify_new_follower()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.follower_id = new.following_id then
    return new;
  end if;

  if not exists (
    select 1 from public.notifications
    where user_id = new.following_id
      and actor_user_id = new.follower_id
      and notification_type = 'new_follower'
  ) then
    insert into public.notifications
      (user_id, actor_user_id, notification_type, entity_type, entity_id)
    values
      (new.following_id, new.follower_id, 'new_follower', 'profile', null);
  end if;

  return new;
end;
$$;

create trigger follows_notify_new_follower
after insert on public.follows
for each row execute function public.notify_new_follower();

create function public.notify_post_like()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_post_owner uuid;
begin
  select user_id into v_post_owner from public.posts where id = new.post_id;

  if v_post_owner is null or v_post_owner = new.user_id then
    return new;
  end if;

  if not exists (
    select 1 from public.notifications
    where user_id = v_post_owner
      and actor_user_id = new.user_id
      and notification_type = 'post_like'
      and entity_id = new.post_id
  ) then
    insert into public.notifications
      (user_id, actor_user_id, notification_type, entity_type, entity_id)
    values
      (v_post_owner, new.user_id, 'post_like', 'post', new.post_id);
  end if;

  return new;
end;
$$;

create trigger post_likes_notify_like
after insert on public.post_likes
for each row execute function public.notify_post_like();

create function public.notify_post_comment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_post_owner uuid;
  v_parent_author uuid;
begin
  if new.parent_comment_id is null then
    select user_id into v_post_owner from public.posts where id = new.post_id;
    if v_post_owner is not null and v_post_owner <> new.user_id then
      insert into public.notifications
        (user_id, actor_user_id, notification_type, entity_type, entity_id)
      values
        (v_post_owner, new.user_id, 'post_comment', 'post', new.post_id);
    end if;
  else
    select user_id into v_parent_author
    from public.post_comments
    where id = new.parent_comment_id;

    if v_parent_author is not null and v_parent_author <> new.user_id then
      insert into public.notifications
        (user_id, actor_user_id, notification_type, entity_type, entity_id)
      values
        (v_parent_author, new.user_id, 'comment_reply', 'comment', new.id);
    end if;
  end if;

  return new;
end;
$$;

create trigger post_comments_notify_comment
after insert on public.post_comments
for each row execute function public.notify_post_comment();

-- Trigger functions are invoked only by their triggers, never called directly.
revoke all on function public.notify_new_follower() from public, anon, authenticated;
revoke all on function public.notify_post_like() from public, anon, authenticated;
revoke all on function public.notify_post_comment() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Notification read RPCs
-- ---------------------------------------------------------------------------

-- The viewer's notifications, newest first, keyset paginated on
-- (created_at, id) — the same shape as list_feed(). For each row resolves the
-- actor's profile (null when the actor's account no longer exists) and
-- whether the underlying target still resolves for this viewer.
--
-- Block policy: a row whose actor is now blocked in either direction is
-- filtered out entirely (never returned) — once a block stands, historical
-- notifications between the two accounts are hidden. This is distinct from
-- the deleted-content policy below: a notification whose target was merely
-- soft-deleted (no block involved) is still returned, because its calm
-- sentence never contained the post/comment body — only its target becomes
-- non-navigable (target_available = false).
create function public.list_notifications(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  notification_type text,
  entity_type text,
  entity_id bigint,
  actor_user_id uuid,
  actor_username text,
  actor_display_name text,
  target_post_id bigint,
  target_available boolean,
  read_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    n.id,
    n.notification_type,
    n.entity_type,
    n.entity_id,
    n.actor_user_id,
    pr.username,
    pr.display_name,
    case
      when n.notification_type in ('post_like', 'post_comment')
        then case when public.viewer_can_see_post(n.entity_id) then n.entity_id else null end
      when n.notification_type = 'comment_reply'
        then case
          when c.deleted_at is null and public.viewer_can_see_post(c.post_id)
            then c.post_id
          else null
        end
      else null
    end,
    case
      when n.notification_type = 'new_follower' then
        exists (
          select 1 from public.profiles p
          where p.id = n.actor_user_id and p.onboarding_completed
        )
      when n.notification_type in ('post_like', 'post_comment') then
        public.viewer_can_see_post(n.entity_id)
      when n.notification_type = 'comment_reply' then
        c.deleted_at is null and public.viewer_can_see_post(c.post_id)
      else false
    end,
    n.read_at,
    n.created_at
  from public.notifications n
  left join public.profiles pr on pr.id = n.actor_user_id
  left join public.post_comments c
    on n.notification_type = 'comment_reply' and c.id = n.entity_id
  where n.user_id = v_viewer
    and (
      n.actor_user_id is null
      or not public.blocked_between(v_viewer, n.actor_user_id)
    )
    and (
      p_before_created_at is null
      or (n.created_at, n.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by n.created_at desc, n.id desc
  limit v_limit;
end;
$$;

-- Unread count, same block filter as list_notifications() so the badge never
-- counts a notification from someone now blocked in either direction.
create function public.get_unread_notification_count()
returns integer
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return (
    select count(*)::integer
    from public.notifications n
    where n.user_id = v_viewer
      and n.read_at is null
      and (
        n.actor_user_id is null
        or not public.blocked_between(v_viewer, n.actor_user_id)
      )
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Notification write RPCs — the only way read state can change
-- ---------------------------------------------------------------------------

create function public.mark_notification_read(p_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  update public.notifications
  set read_at = now()
  where id = p_notification_id
    and user_id = v_viewer
    and read_at is null;
end;
$$;

create function public.mark_all_notifications_read()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  update public.notifications
  set read_at = now()
  where user_id = v_viewer
    and read_at is null;
end;
$$;

-- ---------------------------------------------------------------------------
-- Discover — people
-- ---------------------------------------------------------------------------
-- Deterministic discovery only (no AI / engagement ranking): completed
-- profiles, not the viewer, not already followed, not blocked in either
-- direction, ranked by shared-interest overlap with the viewer then by
-- account age, with a stable final tie-break on id so pagination never skips
-- or repeats a row.

create function public.discover_people(
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  username text,
  display_name text,
  bio text,
  shared_interest_count integer,
  viewer_follows boolean,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.username,
    p.display_name,
    p.bio,
    (
      select count(*)::integer
      from public.user_interests vi
      join public.user_interests ci
        on ci.interest_id = vi.interest_id and ci.user_id = p.id
      where vi.user_id = v_viewer
    ),
    -- Always false here: the WHERE clause below already excludes anyone the
    -- viewer follows. Included for a row shape uniform with search_people().
    false,
    count(*) over ()::bigint
  from public.profiles p
  where p.onboarding_completed
    and p.id <> v_viewer
    and not exists (
      select 1 from public.follows f
      where f.follower_id = v_viewer and f.following_id = p.id
    )
    and not public.blocked_between(v_viewer, p.id)
  order by
    (
      select count(*)::integer
      from public.user_interests vi
      join public.user_interests ci
        on ci.interest_id = vi.interest_id and ci.user_id = p.id
      where vi.user_id = v_viewer
    ) desc,
    p.created_at desc,
    p.id asc
  limit v_limit
  offset v_offset;
end;
$$;

-- ---------------------------------------------------------------------------
-- Discover — posts
-- ---------------------------------------------------------------------------
-- Recent PUBLIC posts only, block filtered, newest first, keyset paginated —
-- the exact same row shape as list_feed() so the application layer can reuse
-- its mapping and the existing PostFeed / PostCard components unchanged.

create function public.list_discover_posts(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer
  from public.posts p
  join public.profiles pr on pr.id = p.user_id and pr.onboarding_completed
  where p.deleted_at is null
    and p.visibility = 'public'
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search — people
-- ---------------------------------------------------------------------------
-- Case-insensitive substring match against username / display_name / bio.
-- Same completed / not-self / not-blocked filters as discover_people(). The
-- query length is re-clamped here as defence in depth; the application layer
-- already validates it before calling.

create function public.search_people(
  p_query text,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  username text,
  display_name text,
  bio text,
  viewer_follows boolean,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_query text := btrim(coalesce(p_query, ''));
  v_pattern text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_query) < 2 or char_length(v_query) > 100 then
    return;
  end if;

  v_pattern := '%' || v_query || '%';

  return query
  select
    p.id,
    p.username,
    p.display_name,
    p.bio,
    exists (
      select 1 from public.follows f
      where f.follower_id = v_viewer and f.following_id = p.id
    ),
    count(*) over ()::bigint
  from public.profiles p
  where p.onboarding_completed
    and p.id <> v_viewer
    and not public.blocked_between(v_viewer, p.id)
    and (
      p.username ilike v_pattern
      or p.display_name ilike v_pattern
      or p.bio ilike v_pattern
    )
  order by
    (p.username ilike (v_query || '%')) desc,
    p.username asc
  limit v_limit
  offset v_offset;
end;
$$;

-- ---------------------------------------------------------------------------
-- Search — posts
-- ---------------------------------------------------------------------------
-- Same visibility membership rule as list_feed() (own + public + followed
-- followers-only, block filtered) restricted to a case-insensitive substring
-- match on the body. No external search service, no full-text index for V1 —
-- see docs/NOTIFICATIONS_DISCOVER_SEARCH.md for the documented performance
-- trade-off.

create function public.search_posts(
  p_query text,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_query text := btrim(coalesce(p_query, ''));
  v_pattern text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_query) < 2 or char_length(v_query) > 100 then
    return;
  end if;

  v_pattern := '%' || v_query || '%';

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer
  from public.posts p
  join public.profiles pr on pr.id = p.user_id
  where p.deleted_at is null
    and p.body ilike v_pattern
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p.user_id = v_viewer
      or p.visibility = 'public'
      or (
        p.visibility = 'followers'
        and exists (
          select 1 from public.follows f
          where f.follower_id = v_viewer and f.following_id = p.user_id
        )
      )
    )
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- ---------------------------------------------------------------------------
-- Execution privileges
-- ---------------------------------------------------------------------------

revoke all on function public.list_notifications(timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_unread_notification_count() from public, anon;
revoke all on function public.mark_notification_read(bigint) from public, anon;
revoke all on function public.mark_all_notifications_read() from public, anon;
revoke all on function public.discover_people(integer, integer) from public, anon;
revoke all on function public.list_discover_posts(timestamptz, bigint, integer) from public, anon;
revoke all on function public.search_people(text, integer, integer) from public, anon;
revoke all on function public.search_posts(text, timestamptz, bigint, integer) from public, anon;

grant execute on function public.list_notifications(timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_unread_notification_count() to authenticated;
grant execute on function public.mark_notification_read(bigint) to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;
grant execute on function public.discover_people(integer, integer) to authenticated;
grant execute on function public.list_discover_posts(timestamptz, bigint, integer) to authenticated;
grant execute on function public.search_people(text, integer, integer) to authenticated;
grant execute on function public.search_posts(text, timestamptz, bigint, integer) to authenticated;

commit;
