begin;

-- Diong Media + Profile Polish — Pass 7.
--
-- Additive only. Adds:
--   * avatar_path / cover_path columns on public.profiles and public.communities
--   * one new table, public.post_media (0-4 images per post)
--   * one new Storage bucket, diong-public-media, and its storage.objects RLS
--   * one ownership-check trigger and one Storage-path-ownership helper function
--   * four new SECURITY DEFINER RPCs: attach_post_media, remove_post_media,
--     set_community_avatar, set_community_cover
--   * a drop-and-recreate of every existing read RPC that returns a user- or
--     community-identity row, adding an avatar_path (and, for post rows, a
--     media jsonb array) trailing column. Recreated because PostgreSQL does
--     not allow CREATE OR REPLACE FUNCTION to change a function's RETURNS
--     TABLE column list — the argument list of every recreated function is
--     byte-for-byte unchanged, so every existing call site keeps compiling.
--     DROP FUNCTION also drops all privileges on the function (unlike CREATE
--     OR REPLACE), so every recreated function's execute privileges are
--     re-asserted (authenticated only, never anon/public) at the end of this
--     file.
--
-- Nothing in this file alters an existing table's pre-existing columns, an
-- existing migration file, or any pre-existing RLS policy. No previously
-- applied migration is edited.
--
-- Apply once, in order, after 202609130001_goals_habits_journal.sql. Depends
-- on public.profiles / public.posts / public.communities / public.blocks
-- (earlier passes) and public.viewer_can_see_post / public.blocked_between /
-- public.community_role (202609100003 / 202609120003). This migration is a
-- single transaction and is NOT idempotent — never re-run a migration that
-- already succeeded.
--
-- Privacy note, documented again in docs/MEDIA_PROFILE_STORAGE.md: the
-- diong-public-media bucket is PUBLIC READ by design (V1 decision — every
-- object placed here is intentionally social/public media). A public object
-- URL is NOT a privacy boundary: once a client has fetched a direct Storage
-- URL, that URL may remain technically retrievable even after the app UI
-- later hides the associated content (for example, a post image belonging to
-- an author the viewer subsequently blocks). Filenames are unpredictable
-- UUIDs precisely to make this an acceptable V1 trade-off, not a hard
-- guarantee of unlinkability.

-- ---------------------------------------------------------------------------
-- 1. Profile & community media columns
-- ---------------------------------------------------------------------------
-- avatar_url (profiles) predates this migration, was never wired to any
-- upload path, and is left untouched here — avatar_path is the Pass 7
-- storage-backed column going forward. A future pass may drop avatar_url.

alter table public.profiles
  add column avatar_path text,
  add column cover_path text;

-- Column-scoped grant is additive: this does not remove the existing
-- (username, display_name, bio, avatar_url, onboarding_completed) grant from
-- 202607190001. The existing "Users can update their own profile" RLS policy
-- already covers these two new columns (it is not column-scoped).
grant update (avatar_path, cover_path) on public.profiles to authenticated;

alter table public.communities
  add column avatar_path text,
  add column cover_path text;
-- No column grant needed: public.communities has no direct client write
-- grant at all (RPC-only since 202609120003), and stays that way — community
-- avatar/cover are written only by the new set_community_avatar /
-- set_community_cover RPCs below.

-- ---------------------------------------------------------------------------
-- 2. post_media
-- ---------------------------------------------------------------------------

create table public.post_media (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  mime_type text not null,
  size_bytes bigint not null,
  width integer,
  height integer,
  position integer not null default 0,
  alt_text text,
  created_at timestamptz not null default now(),
  constraint post_media_mime_type_allowed
    check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  constraint post_media_size_bytes_positive check (size_bytes > 0),
  -- 6291456 = 6 MiB, the V1 post-image cap. Avatar (3 MB) / cover (5 MB)
  -- limits are enforced in the application layer (profiles/communities carry
  -- no size_bytes column), not here.
  constraint post_media_size_bytes_max check (size_bytes <= 6291456),
  constraint post_media_position_non_negative check (position >= 0),
  constraint post_media_alt_text_length
    check (alt_text is null or char_length(alt_text) <= 300),
  constraint post_media_storage_path_not_blank check (char_length(storage_path) > 0),
  constraint post_media_storage_path_unique unique (storage_path),
  -- Also the target of the composite FK used nowhere else, but doubles as the
  -- "at most one row per (post, slot)" invariant that assigns display order.
  constraint post_media_post_position_unique unique (post_id, position)
);

create index post_media_post_position_idx on public.post_media (post_id, position);
create index post_media_user_created_idx on public.post_media (user_id, created_at desc);

-- Defence in depth: attach_post_media() below already checks post ownership
-- before inserting, but this trigger keeps "media.user_id = post's author"
-- true no matter how a row is inserted or updated.
create function public.enforce_post_media_ownership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.user_id <> (select p.user_id from public.posts p where p.id = new.post_id) then
    raise exception using errcode = '42501',
      message = 'Media must belong to the post author.';
  end if;
  return new;
end;
$$;

create trigger post_media_enforce_ownership
before insert or update on public.post_media
for each row execute function public.enforce_post_media_ownership();

alter table public.post_media enable row level security;

revoke all on public.post_media from anon, authenticated;

-- post_media is RPC-only: attach_post_media() / remove_post_media() are the
-- only write path (security definer, bypasses this grant/RLS entirely). This
-- select grant + policy exist purely as a defence-in-depth floor for any
-- future direct query — every existing read RPC that surfaces media reads
-- public.post_media internally as SECURITY DEFINER and does not depend on
-- this grant.
grant select on public.post_media to authenticated;

create policy "Read media on visible posts"
on public.post_media for select
to authenticated
using (public.viewer_can_see_post(post_id));

-- ---------------------------------------------------------------------------
-- 3. Storage bucket, ownership helper, storage.objects RLS
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'diong-public-media',
  'diong-public-media',
  true,
  6291456,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

-- Parses a diong-public-media object path and confirms auth.uid() owns the
-- resource it names, for the three path shapes defined in
-- docs/MEDIA_PROFILE_STORAGE.md:
--   profiles/{userId}/avatar|cover/{uuid}.{ext}                (3 segments)
--   posts/{userId}/{postId}/{uuid}.{ext}                       (3 segments)
--   communities/{ownerUserId}/{communityId}/avatar|cover/{uuid}.{ext} (4 segments)
-- SECURITY DEFINER so it can read public.posts / public.communities as the
-- function owner regardless of the caller's own RLS visibility of those
-- rows — the same reasoning as public.community_role() /
-- public.is_community_banned() reading tables the client cannot select
-- directly. Numeric segments are regex-checked before casting to bigint so a
-- malformed path is rejected (returns false) rather than raising.
create function public.media_path_owner_ok(p_name text)
returns boolean
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_segments text[];
begin
  if v_viewer is null or p_name is null then
    return false;
  end if;

  v_segments := storage.foldername(p_name);

  if v_segments is null or coalesce(array_length(v_segments, 1), 0) = 0 then
    return false;
  end if;

  if v_segments[1] = 'profiles' then
    return array_length(v_segments, 1) = 3
      and v_segments[2] = v_viewer::text
      and v_segments[3] in ('avatar', 'cover');
  end if;

  if v_segments[1] = 'posts' then
    return array_length(v_segments, 1) = 3
      and v_segments[2] = v_viewer::text
      and v_segments[3] ~ '^[0-9]+$'
      and exists (
        select 1 from public.posts
        where id = v_segments[3]::bigint and user_id = v_viewer
      );
  end if;

  if v_segments[1] = 'communities' then
    return array_length(v_segments, 1) = 4
      and v_segments[2] = v_viewer::text
      and v_segments[3] ~ '^[0-9]+$'
      and v_segments[4] in ('avatar', 'cover')
      and exists (
        select 1 from public.communities
        where id = v_segments[3]::bigint and owner_id = v_viewer
      );
  end if;

  return false;
end;
$$;

-- Public read (the bucket is public by design — see the privacy note at the
-- top of this file). Authenticated-only, ownership-checked insert/delete. No
-- update policy: every path segment ends in a freshly generated UUID
-- filename, so an in-place overwrite is never part of the upload flow —
-- replacement always uploads a new object under a new name.
create policy "Public read for diong-public-media"
on storage.objects for select
to public
using (bucket_id = 'diong-public-media');

create policy "Owners can upload to their own diong-public-media path"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'diong-public-media'
  and public.media_path_owner_ok(name)
);

create policy "Owners can delete their own diong-public-media objects"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'diong-public-media'
  and public.media_path_owner_ok(name)
);

-- ---------------------------------------------------------------------------
-- 4. New mutation RPCs
-- ---------------------------------------------------------------------------

-- Attaches one already-uploaded Storage object to a post the caller owns.
-- Assumes the object itself was already ownership/type/size checked by the
-- Storage RLS policies and bucket config above; this RPC re-validates mime
-- type, size and the storage_path's expected prefix as the authoritative,
-- non-bypassable check (never trusts the client's claims alone), assigns the
-- next available position, and enforces the 4-image-per-post ceiling.
create function public.attach_post_media(
  p_post_id bigint,
  p_storage_path text,
  p_mime_type text,
  p_size_bytes bigint,
  p_width integer default null,
  p_height integer default null,
  p_alt_text text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_alt_text text := nullif(btrim(coalesce(p_alt_text, '')), '');
  v_expected_prefix text;
  v_next_position integer;
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.posts
    where id = p_post_id and user_id = v_viewer and deleted_at is null
  ) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  if p_mime_type is null or p_mime_type not in ('image/jpeg', 'image/png', 'image/webp') then
    raise exception using errcode = '22023', message = 'Choose a JPEG, PNG or WEBP image.';
  end if;

  if p_size_bytes is null or p_size_bytes <= 0 or p_size_bytes > 6291456 then
    raise exception using errcode = '22023', message = 'Image must be 6 MB or smaller.';
  end if;

  if v_alt_text is not null and char_length(v_alt_text) > 300 then
    raise exception using errcode = '22023', message = 'Alt text must be 300 characters or fewer.';
  end if;

  v_expected_prefix := 'posts/' || v_viewer::text || '/' || p_post_id::text || '/';
  if p_storage_path is null
     or char_length(p_storage_path) = 0
     or left(p_storage_path, char_length(v_expected_prefix)) <> v_expected_prefix
  then
    raise exception using errcode = '42501', message = 'This image cannot be attached.';
  end if;

  if (select count(*) from public.post_media where post_id = p_post_id) >= 4 then
    raise exception using errcode = '23514', message = 'A post can have at most 4 images.';
  end if;

  select coalesce(max(position) + 1, 0) into v_next_position
  from public.post_media where post_id = p_post_id;

  insert into public.post_media
    (post_id, user_id, storage_path, mime_type, size_bytes, width, height, position, alt_text)
  values
    (p_post_id, v_viewer, p_storage_path, p_mime_type, p_size_bytes, p_width, p_height, v_next_position, v_alt_text)
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- Removes one of the caller's own post_media rows and returns its
-- storage_path so the calling Server Action can delete the Storage object
-- after this DB write has succeeded.
create function public.remove_post_media(p_media_id bigint)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_storage_path text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  delete from public.post_media
  where id = p_media_id and user_id = v_viewer
  returning storage_path into v_storage_path;

  if not found then
    raise exception using errcode = '42501', message = 'This image is not available.';
  end if;

  return v_storage_path;
end;
$$;

-- Owner-only. p_storage_path = null removes the community avatar.
create function public.set_community_avatar(
  p_community_id bigint,
  p_storage_path text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_expected_prefix text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and owner_id = v_viewer
  ) then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  if p_storage_path is not null then
    v_expected_prefix := 'communities/' || v_viewer::text || '/' || p_community_id::text || '/avatar/';
    if left(p_storage_path, char_length(v_expected_prefix)) <> v_expected_prefix then
      raise exception using errcode = '42501', message = 'This image cannot be used.';
    end if;
  end if;

  update public.communities
  set avatar_path = p_storage_path
  where id = p_community_id;
end;
$$;

-- Owner-only. p_storage_path = null removes the community cover.
create function public.set_community_cover(
  p_community_id bigint,
  p_storage_path text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_expected_prefix text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and owner_id = v_viewer
  ) then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  if p_storage_path is not null then
    v_expected_prefix := 'communities/' || v_viewer::text || '/' || p_community_id::text || '/cover/';
    if left(p_storage_path, char_length(v_expected_prefix)) <> v_expected_prefix then
      raise exception using errcode = '42501', message = 'This image cannot be used.';
    end if;
  end if;

  update public.communities
  set cover_path = p_storage_path
  where id = p_community_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Extend existing read RPCs with avatar_path / cover_path / media
-- ---------------------------------------------------------------------------
-- Every function below is dropped then recreated with the SAME argument list
-- as its prior definition (see the migrations named in each comment) and one
-- or two new TRAILING output columns. Bodies are otherwise byte-for-byte
-- copied from the prior definition. This is required because PostgreSQL
-- disallows CREATE OR REPLACE FUNCTION from changing a RETURNS TABLE column
-- list.

-- From 202609120001_fix_social_profile_username.sql. Adds avatar_path,
-- cover_path.
drop function public.get_social_profile(text);

create function public.get_social_profile(p_username text)
returns table (
  id uuid,
  username text,
  display_name text,
  bio text,
  follower_count integer,
  following_count integer,
  is_self boolean,
  viewer_follows boolean,
  viewer_blocked boolean,
  avatar_path text,
  cover_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  normalized text := lower(btrim(coalesce(p_username, '')));
  target public.profiles;
  v_is_self boolean;
  v_blocked_by boolean;
  v_viewer_blocked boolean;
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if normalized !~ '^[a-z0-9_]{3,30}$' then
    return;
  end if;

  select * into target
  from public.profiles
  where profiles.username = normalized
    and profiles.onboarding_completed;

  if not found then
    return;
  end if;

  v_is_self := target.id = current_user_id;

  v_blocked_by := (not v_is_self) and exists (
    select 1 from public.blocks
    where blocker_id = target.id and blocked_id = current_user_id
  );
  if v_blocked_by then
    return;
  end if;

  v_viewer_blocked := (not v_is_self) and exists (
    select 1 from public.blocks
    where blocker_id = current_user_id and blocked_id = target.id
  );

  return query
  select
    target.id,
    target.username,
    target.display_name,
    case when v_viewer_blocked then null else target.bio end,
    case
      when v_viewer_blocked then null
      else (select count(*)::integer from public.follows where following_id = target.id)
    end,
    case
      when v_viewer_blocked then null
      else (select count(*)::integer from public.follows where follower_id = target.id)
    end,
    v_is_self,
    (not v_is_self) and exists (
      select 1 from public.follows
      where follower_id = current_user_id and following_id = target.id
    ),
    v_viewer_blocked,
    case when v_viewer_blocked then null else target.avatar_path end,
    case when v_viewer_blocked then null else target.cover_path end;
end;
$$;

-- From 202609100004_notifications_discover_search.sql. Adds avatar_path.
drop function public.discover_people(integer, integer);

create function public.discover_people(
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  username text,
  display_name text,
  bio text,
  shared_interest_count integer,
  viewer_follows boolean,
  total_count bigint,
  avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.username,
    p.display_name,
    p.bio,
    (
      select count(*)::integer
      from public.user_interests vi
      join public.user_interests ci
        on ci.interest_id = vi.interest_id and ci.user_id = p.id
      where vi.user_id = v_viewer
    ),
    false,
    count(*) over ()::bigint,
    p.avatar_path
  from public.profiles p
  where p.onboarding_completed
    and p.id <> v_viewer
    and not exists (
      select 1 from public.follows f
      where f.follower_id = v_viewer and f.following_id = p.id
    )
    and not public.blocked_between(v_viewer, p.id)
  order by
    (
      select count(*)::integer
      from public.user_interests vi
      join public.user_interests ci
        on ci.interest_id = vi.interest_id and ci.user_id = p.id
      where vi.user_id = v_viewer
    ) desc,
    p.created_at desc,
    p.id asc
  limit v_limit
  offset v_offset;
end;
$$;

-- From 202609100004_notifications_discover_search.sql. Adds avatar_path.
drop function public.search_people(text, integer, integer);

create function public.search_people(
  p_query text,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  username text,
  display_name text,
  bio text,
  viewer_follows boolean,
  total_count bigint,
  avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_query text := btrim(coalesce(p_query, ''));
  v_pattern text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_query) < 2 or char_length(v_query) > 100 then
    return;
  end if;

  v_pattern := '%' || v_query || '%';

  return query
  select
    p.id,
    p.username,
    p.display_name,
    p.bio,
    exists (
      select 1 from public.follows f
      where f.follower_id = v_viewer and f.following_id = p.id
    ),
    count(*) over ()::bigint,
    p.avatar_path
  from public.profiles p
  where p.onboarding_completed
    and p.id <> v_viewer
    and not public.blocked_between(v_viewer, p.id)
    and (
      p.username ilike v_pattern
      or p.display_name ilike v_pattern
      or p.bio ilike v_pattern
    )
  order by
    (p.username ilike (v_query || '%')) desc,
    p.username asc
  limit v_limit
  offset v_offset;
end;
$$;

-- Shared post-media aggregation used by every post-row RPC below: a
-- position-ordered jsonb array, '[]' when the post has no images.
-- (Inlined per call site rather than a helper function, matching the
-- existing repo convention of inlining per-post subqueries such as
-- like_count / comment_count rather than factoring them out.)

-- From 202609100003_social_content.sql. Adds author_avatar_path, media.
drop function public.list_feed(timestamptz, bigint, integer);

create function public.list_feed(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.posts p
  join public.profiles pr on pr.id = p.user_id and pr.onboarding_completed
  where p.deleted_at is null
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p.user_id = v_viewer
      or p.visibility = 'public'
      or (
        p.visibility = 'followers'
        and exists (
          select 1 from public.follows f
          where f.follower_id = v_viewer and f.following_id = p.user_id
        )
      )
    )
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- From 202609100003_social_content.sql. Adds author_avatar_path, media.
drop function public.get_post(bigint);

create function public.get_post(p_post_id bigint)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    return;
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.posts p
  join public.profiles pr on pr.id = p.user_id
  where p.id = p_post_id;
end;
$$;

-- From 202609100003_social_content.sql. Adds author_avatar_path, media.
drop function public.list_user_posts(uuid, timestamptz, bigint, integer);

create function public.list_user_posts(
  p_author_id uuid,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if p_author_id is null or public.blocked_between(v_viewer, p_author_id) then
    return;
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.posts p
  join public.profiles pr on pr.id = p.user_id
  where p.user_id = p_author_id
    and p.deleted_at is null
    and (
      p.user_id = v_viewer
      or p.visibility = 'public'
      or (
        p.visibility = 'followers'
        and exists (
          select 1 from public.follows f
          where f.follower_id = v_viewer and f.following_id = p.user_id
        )
      )
    )
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- From 202609100004_notifications_discover_search.sql. Adds
-- author_avatar_path, media.
drop function public.list_discover_posts(timestamptz, bigint, integer);

create function public.list_discover_posts(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.posts p
  join public.profiles pr on pr.id = p.user_id and pr.onboarding_completed
  where p.deleted_at is null
    and p.visibility = 'public'
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- From 202609100004_notifications_discover_search.sql. Adds
-- author_avatar_path, media.
drop function public.search_posts(text, timestamptz, bigint, integer);

create function public.search_posts(
  p_query text,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_query text := btrim(coalesce(p_query, ''));
  v_pattern text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_query) < 2 or char_length(v_query) > 100 then
    return;
  end if;

  v_pattern := '%' || v_query || '%';

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.posts p
  join public.profiles pr on pr.id = p.user_id
  where p.deleted_at is null
    and p.body ilike v_pattern
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p.user_id = v_viewer
      or p.visibility = 'public'
      or (
        p.visibility = 'followers'
        and exists (
          select 1 from public.follows f
          where f.follower_id = v_viewer and f.following_id = p.user_id
        )
      )
    )
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- From 202609120003_communities.sql. Adds author_avatar_path, media.
drop function public.list_community_posts(bigint, timestamptz, bigint, integer);

create function public.list_community_posts(
  p_community_id bigint,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.community_post_links l
  join public.posts p on p.id = l.post_id
  join public.profiles pr on pr.id = p.user_id
  where l.community_id = p_community_id
    and l.removed_at is null
    and p.deleted_at is null
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- From 202609100003_social_content.sql. Adds author_avatar_path, media.
drop function public.list_bookmarks(timestamptz, bigint, integer);

create function public.list_bookmarks(
  p_before_created_at timestamptz default null,
  p_before_post_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  bookmarked_at timestamptz,
  author_avatar_path text,
  media jsonb
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb2
      where pb2.post_id = p.id and pb2.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pb.created_at,
    pr.avatar_path,
    (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', pm.id,
        'storage_path', pm.storage_path,
        'width', pm.width,
        'height', pm.height,
        'position', pm.position,
        'alt_text', pm.alt_text
      ) order by pm.position), '[]'::jsonb)
      from public.post_media pm
      where pm.post_id = p.id
    )
  from public.post_bookmarks pb
  join public.posts p on p.id = pb.post_id
  join public.profiles pr on pr.id = p.user_id
  where pb.user_id = v_viewer
    and public.viewer_can_see_post(p.id)
    and (
      p_before_created_at is null
      or (pb.created_at, pb.post_id)
         < (p_before_created_at, coalesce(p_before_post_id, 9223372036854775807))
    )
  order by pb.created_at desc, pb.post_id desc
  limit v_limit;
end;
$$;

-- From 202609100003_social_content.sql. Adds author_avatar_path (commenter's
-- avatar). No media — comments do not carry images.
drop function public.list_post_comments(bigint);

create function public.list_post_comments(p_post_id bigint)
returns table (
  id bigint,
  parent_comment_id bigint,
  user_id uuid,
  author_username text,
  author_display_name text,
  body text,
  created_at timestamptz,
  edited_at timestamptz,
  is_deleted boolean,
  is_author boolean,
  author_avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    return;
  end if;

  return query
  select
    c.id,
    c.parent_comment_id,
    c.user_id,
    pr.username,
    pr.display_name,
    case when c.deleted_at is null then c.body else null end,
    c.created_at,
    c.edited_at,
    c.deleted_at is not null,
    c.user_id = v_viewer,
    pr.avatar_path
  from public.post_comments c
  join public.profiles pr on pr.id = c.user_id
  where c.post_id = p_post_id
    and not public.blocked_between(v_viewer, c.user_id)
    and (
      c.deleted_at is null
      or (
        c.parent_comment_id is null
        and exists (
          select 1 from public.post_comments r
          where r.parent_comment_id = c.id and r.deleted_at is null
        )
      )
    )
  order by
    coalesce(c.parent_comment_id, c.id),
    (c.parent_comment_id is not null),
    c.created_at,
    c.id
  limit 500;
end;
$$;

-- From 202609120002_direct_messages.sql (itself a recreation of the
-- 202609100004 original). Adds actor_avatar_path. Every branch below is
-- otherwise unchanged from that most recent definition.
drop function public.list_notifications(timestamptz, bigint, integer);

create function public.list_notifications(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  notification_type text,
  entity_type text,
  entity_id bigint,
  actor_user_id uuid,
  actor_username text,
  actor_display_name text,
  target_post_id bigint,
  target_available boolean,
  read_at timestamptz,
  created_at timestamptz,
  actor_avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    n.id,
    n.notification_type,
    n.entity_type,
    n.entity_id,
    n.actor_user_id,
    pr.username,
    pr.display_name,
    case
      when n.notification_type in ('post_like', 'post_comment')
        then case when public.viewer_can_see_post(n.entity_id) then n.entity_id else null end
      when n.notification_type = 'comment_reply'
        then case
          when c.deleted_at is null and public.viewer_can_see_post(c.post_id)
            then c.post_id
          else null
        end
      else null
    end,
    case
      when n.notification_type = 'new_follower' then
        exists (
          select 1 from public.profiles p
          where p.id = n.actor_user_id and p.onboarding_completed
        )
      when n.notification_type in ('post_like', 'post_comment') then
        public.viewer_can_see_post(n.entity_id)
      when n.notification_type = 'comment_reply' then
        c.deleted_at is null and public.viewer_can_see_post(c.post_id)
      when n.notification_type = 'new_message' then
        public.is_conversation_member(n.entity_id, v_viewer)
      else false
    end,
    n.read_at,
    n.created_at,
    pr.avatar_path
  from public.notifications n
  left join public.profiles pr on pr.id = n.actor_user_id
  left join public.post_comments c
    on n.notification_type = 'comment_reply' and c.id = n.entity_id
  where n.user_id = v_viewer
    and (
      n.actor_user_id is null
      or not public.blocked_between(v_viewer, n.actor_user_id)
    )
    and (
      p_before_created_at is null
      or (n.created_at, n.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by n.created_at desc, n.id desc
  limit v_limit;
end;
$$;

-- From 202609120002_direct_messages.sql. Adds other_avatar_path.
drop function public.list_conversations(timestamptz, bigint, integer);

create function public.list_conversations(
  p_before_last_message_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  other_user_id uuid,
  other_username text,
  other_display_name text,
  last_message_body text,
  last_message_at timestamptz,
  unread boolean,
  other_avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    pr.id,
    pr.username,
    pr.display_name,
    lm.body,
    c.last_message_at,
    (
      lm.created_at is not null
      and lm.sender_id <> v_viewer
      and lm.created_at > coalesce(cm.last_read_at, '-infinity'::timestamptz)
    ),
    pr.avatar_path
  from public.conversation_members cm
  join public.conversations c on c.id = cm.conversation_id
  join public.conversation_members other_cm
    on other_cm.conversation_id = c.id and other_cm.user_id <> v_viewer
  join public.profiles pr on pr.id = other_cm.user_id
  left join lateral (
    select m.body, m.created_at, m.sender_id
    from public.messages m
    where m.conversation_id = c.id
    order by m.created_at desc, m.id desc
    limit 1
  ) lm on true
  where cm.user_id = v_viewer
    and c.last_message_at is not null
    and not public.blocked_between(v_viewer, other_cm.user_id)
    and (
      p_before_last_message_at is null
      or (c.last_message_at, c.id)
         < (p_before_last_message_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by c.last_message_at desc, c.id desc
  limit v_limit;
end;
$$;

-- From 202609120002_direct_messages.sql. Adds other_avatar_path.
drop function public.get_conversation(bigint);

create function public.get_conversation(p_conversation_id bigint)
returns table (
  id bigint,
  other_user_id uuid,
  other_username text,
  other_display_name text,
  created_at timestamptz,
  other_avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.is_conversation_member(p_conversation_id, v_viewer) then
    return;
  end if;

  return query
  select
    c.id,
    pr.id,
    pr.username,
    pr.display_name,
    c.created_at,
    pr.avatar_path
  from public.conversations c
  join public.conversation_members cm
    on cm.conversation_id = c.id and cm.user_id <> v_viewer
  join public.profiles pr on pr.id = cm.user_id
  where c.id = p_conversation_id
    and not public.blocked_between(v_viewer, cm.user_id);
end;
$$;

-- From 202609120003_communities.sql. Adds avatar_path, cover_path.
drop function public.get_community(text);

create function public.get_community(p_slug text)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  rules text,
  owner_id uuid,
  owner_username text,
  owner_display_name text,
  member_count integer,
  created_at timestamptz,
  viewer_role text,
  avatar_path text,
  cover_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    c.rules,
    c.owner_id,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.community_members m where m.community_id = c.id),
    c.created_at,
    public.community_role(c.id, v_viewer),
    c.avatar_path,
    c.cover_path
  from public.communities c
  join public.profiles pr on pr.id = c.owner_id
  where c.slug = lower(btrim(coalesce(p_slug, '')))
    and c.is_active;
end;
$$;

-- From 202609120003_communities.sql. Adds avatar_path.
drop function public.list_my_communities(integer, integer);

create function public.list_my_communities(
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  member_count integer,
  viewer_role text,
  total_count bigint,
  avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    (select count(*)::integer from public.community_members m2 where m2.community_id = c.id),
    cm.role,
    count(*) over (),
    c.avatar_path
  from public.community_members cm
  join public.communities c on c.id = cm.community_id and c.is_active
  where cm.user_id = v_viewer
  order by c.name asc, c.id asc
  limit v_limit offset v_offset;
end;
$$;

-- From 202609120003_communities.sql. Adds avatar_path.
drop function public.list_discover_communities(integer, integer);

create function public.list_discover_communities(
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  member_count integer,
  total_count bigint,
  avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    (select count(*)::integer from public.community_members m where m.community_id = c.id),
    count(*) over (),
    c.avatar_path
  from public.communities c
  where c.is_active
    and not exists (
      select 1 from public.community_members m
      where m.community_id = c.id and m.user_id = v_viewer
    )
    and not public.is_community_banned(c.id, v_viewer)
  order by c.created_at desc, c.id desc
  limit v_limit offset v_offset;
end;
$$;

-- From 202609120003_communities.sql. Adds avatar_path.
drop function public.search_communities(text, integer, integer);

create function public.search_communities(
  p_query text,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  member_count integer,
  viewer_joined boolean,
  total_count bigint,
  avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_query text := btrim(coalesce(p_query, ''));
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_query) < 2 then
    return;
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    (select count(*)::integer from public.community_members m2 where m2.community_id = c.id),
    exists (
      select 1 from public.community_members m3
      where m3.community_id = c.id and m3.user_id = v_viewer
    ),
    count(*) over (),
    c.avatar_path
  from public.communities c
  where c.is_active
    and (
      c.name ilike '%' || v_query || '%'
      or c.slug ilike '%' || v_query || '%'
      or c.description ilike '%' || v_query || '%'
    )
  order by (c.name ilike v_query || '%') desc, c.name asc, c.id asc
  limit v_limit offset v_offset;
end;
$$;

-- From 202609120003_communities.sql. Adds avatar_path.
drop function public.list_community_members(bigint, integer, integer);

create function public.list_community_members(
  p_community_id bigint,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  user_id uuid,
  username text,
  display_name text,
  role text,
  joined_at timestamptz,
  total_count bigint,
  avatar_path text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and is_active
  ) then
    return;
  end if;

  return query
  select
    m.user_id,
    pr.username,
    pr.display_name,
    m.role,
    m.joined_at,
    count(*) over (),
    pr.avatar_path
  from public.community_members m
  join public.profiles pr on pr.id = m.user_id
  where m.community_id = p_community_id
    and not public.blocked_between(v_viewer, m.user_id)
  order by
    case m.role when 'owner' then 0 when 'moderator' then 1 else 2 end,
    m.joined_at asc,
    m.user_id asc
  limit v_limit offset v_offset;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. Execution privileges
-- ---------------------------------------------------------------------------
-- New functions, plus every function dropped-and-recreated in section 5
-- above (DROP FUNCTION discards all privileges, unlike CREATE OR REPLACE — so
-- each of these needs an explicit re-grant; a bare CREATE FUNCTION otherwise
-- defaults to EXECUTE granted to PUBLIC, which would silently re-open every
-- one of these RPCs to the anon role).

revoke all on function public.enforce_post_media_ownership() from public, anon, authenticated;

revoke all on function public.media_path_owner_ok(text) from public, anon;
grant execute on function public.media_path_owner_ok(text) to authenticated;

revoke all on function public.attach_post_media(bigint, text, text, bigint, integer, integer, text) from public, anon;
revoke all on function public.remove_post_media(bigint) from public, anon;
revoke all on function public.set_community_avatar(bigint, text) from public, anon;
revoke all on function public.set_community_cover(bigint, text) from public, anon;

grant execute on function public.attach_post_media(bigint, text, text, bigint, integer, integer, text) to authenticated;
grant execute on function public.remove_post_media(bigint) to authenticated;
grant execute on function public.set_community_avatar(bigint, text) to authenticated;
grant execute on function public.set_community_cover(bigint, text) to authenticated;

revoke all on function public.get_social_profile(text) from public, anon;
revoke all on function public.discover_people(integer, integer) from public, anon;
revoke all on function public.search_people(text, integer, integer) from public, anon;
revoke all on function public.list_feed(timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_post(bigint) from public, anon;
revoke all on function public.list_user_posts(uuid, timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_discover_posts(timestamptz, bigint, integer) from public, anon;
revoke all on function public.search_posts(text, timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_community_posts(bigint, timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_bookmarks(timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_post_comments(bigint) from public, anon;
revoke all on function public.list_notifications(timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_conversations(timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_conversation(bigint) from public, anon;
revoke all on function public.get_community(text) from public, anon;
revoke all on function public.list_my_communities(integer, integer) from public, anon;
revoke all on function public.list_discover_communities(integer, integer) from public, anon;
revoke all on function public.search_communities(text, integer, integer) from public, anon;
revoke all on function public.list_community_members(bigint, integer, integer) from public, anon;

grant execute on function public.get_social_profile(text) to authenticated;
grant execute on function public.discover_people(integer, integer) to authenticated;
grant execute on function public.search_people(text, integer, integer) to authenticated;
grant execute on function public.list_feed(timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_post(bigint) to authenticated;
grant execute on function public.list_user_posts(uuid, timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_discover_posts(timestamptz, bigint, integer) to authenticated;
grant execute on function public.search_posts(text, timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_community_posts(bigint, timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_bookmarks(timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_post_comments(bigint) to authenticated;
grant execute on function public.list_notifications(timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_conversations(timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_conversation(bigint) to authenticated;
grant execute on function public.get_community(text) to authenticated;
grant execute on function public.list_my_communities(integer, integer) to authenticated;
grant execute on function public.list_discover_communities(integer, integer) to authenticated;
grant execute on function public.search_communities(text, integer, integer) to authenticated;
grant execute on function public.list_community_members(bigint, integer, integer) to authenticated;

commit;
