begin;

-- Diong Communities — Social Network Pass 5: communities, membership,
-- moderation, bans and reporting.
--
-- Additive only. Adds five tables (public.communities, public.community_members,
-- public.community_post_links, public.community_bans, public.reports), their
-- RLS, two internal helper functions and the SECURITY DEFINER RPCs that are the
-- only read path for community / member / post / report lists and the only
-- write path for creating a community, joining/leaving, posting into a
-- community, moderation actions and reporting. Nothing in this file alters an
-- existing table, function, grant, policy or trigger. Daily Prime, Prime
-- history / reflections, Connections, the Pass 1 follow / block graph, the
-- Pass 2 post/comment/like/bookmark semantics, the Pass 3 Discover / Search
-- read paths and the Pass 4 direct-message model are untouched.
--
-- Apply once, in order, after 202609120002_direct_messages.sql. Depends on
-- public.profiles / auth.users (202607190001), public.follows / public.blocks
-- / public.blocked_between (202609100002 / 202609100003) and public.posts /
-- public.viewer_can_see_post (202609100003). Each migration is a single
-- transaction and is NOT idempotent — never re-run a migration that already
-- succeeded.
--
-- V1 design decision: communities are PUBLIC only. Any authenticated user
-- with a completed profile can read an active community, its member list and
-- its post feed. Membership is required only to create a community post.
-- Private / invite-only communities are deferred. There is no owner-transfer
-- feature in V1: the owner recorded at creation time can never leave and can
-- never be removed, demoted or banned by a moderator.
--
-- Community posts reuse the existing public.posts / post_comments /
-- post_likes / post_bookmarks system rather than forking a second post
-- ecosystem. A community post is always created with visibility = 'public'
-- and is linked via public.community_post_links. Moderator "removal" sets
-- removed_at/removed_by/removal_reason on the LINK row only — it removes the
-- post FROM THE COMMUNITY. The underlying public.posts row is never deleted
-- by community moderation; it continues to exist and remain visible through
-- normal Diong post visibility (feed, profile, direct link) unless its author
-- separately edits/soft-deletes it or platform moderation acts on it.
--
-- Reports schema deviation from the brief's literal field list: the brief's
-- suggested public.reports shape uses a single `target_id bigint`, which
-- fits post / comment / community / community_post targets (all bigint ids)
-- but not a `profile` target, whose id is a uuid (auth.users.id). Rather than
-- overload target_id with a text cast (which would defeat foreign-key-style
-- reasoning and make the CHECK constraints far less legible), this migration
-- adds one further nullable column, target_user_id uuid, used only for
-- target_type = 'profile'. This is additive to the brief, not a departure
-- from it, and is the same polymorphic-target idea Pass 3's notifications
-- table already uses (entity_type ties to exactly one entity_id shape) —
-- here a CHECK constraint ties target_type to exactly one of
-- (target_id, target_user_id) being set.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.communities (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  slug text not null unique,
  name text not null,
  description text not null default '',
  rules text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_active boolean not null default true,
  constraint communities_name_length check (char_length(btrim(name)) between 2 and 80),
  constraint communities_slug_format
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) between 3 and 60),
  constraint communities_description_length check (char_length(description) <= 2000),
  constraint communities_rules_length check (char_length(rules) <= 5000)
);

create table public.community_members (
  community_id bigint not null references public.communities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  joined_at timestamptz not null default now(),
  primary key (community_id, user_id),
  constraint community_members_role_allowed check (role in ('owner', 'moderator', 'member'))
);

-- One row per community post. post_id is unique — a post belongs to at most
-- one community. Moderator removal is recorded here (removed_at /
-- removed_by / removal_reason); the underlying post is never touched.
create table public.community_post_links (
  community_id bigint not null references public.communities(id) on delete cascade,
  post_id bigint not null unique references public.posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  removed_at timestamptz,
  removed_by uuid references auth.users(id) on delete set null,
  removal_reason text,
  constraint community_post_links_removal_reason_length
    check (removal_reason is null or char_length(removal_reason) <= 500),
  primary key (community_id, post_id)
);

-- Distinct from Diong's global user block (public.blocks). A community ban is
-- scoped to one community only and never affects the global follow/block
-- graph, direct messages, or any other community.
create table public.community_bans (
  community_id bigint not null references public.communities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  banned_by uuid references auth.users(id) on delete set null,
  reason text,
  created_at timestamptz not null default now(),
  constraint community_bans_reason_length check (reason is null or char_length(reason) <= 500),
  primary key (community_id, user_id)
);

create table public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null,
  target_id bigint,
  target_user_id uuid references auth.users(id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  constraint reports_target_type_allowed check (target_type in (
    'post', 'comment', 'profile', 'community', 'community_post'
  )),
  constraint reports_reason_allowed check (reason in (
    'spam', 'harassment', 'hate_or_abuse', 'unsafe_content',
    'misinformation', 'impersonation', 'other'
  )),
  constraint reports_status_allowed check (status in (
    'open', 'reviewed', 'actioned', 'dismissed'
  )),
  constraint reports_details_length check (details is null or char_length(details) <= 2000),
  -- Exactly one target reference: target_user_id for a profile report,
  -- target_id (a bigint entity id) for every other target type.
  constraint reports_target_shape check (
    (target_type = 'profile' and target_user_id is not null and target_id is null)
    or (target_type <> 'profile' and target_id is not null and target_user_id is null)
  )
);

-- Practical duplicate-spam guard: one open report per (reporter, exact
-- target) at a time. A reporter may report the same target again once the
-- earlier report is reviewed/actioned/dismissed.
create unique index reports_reporter_target_open_unique_idx
  on public.reports (
    reporter_id,
    target_type,
    coalesce(target_id, -1),
    coalesce(target_user_id, '00000000-0000-0000-0000-000000000000'::uuid)
  )
  where status = 'open';

create index communities_slug_idx on public.communities (slug);
create index communities_created_idx on public.communities (created_at desc, id desc);

create index community_members_user_id_idx on public.community_members (user_id);
create index community_members_role_idx on public.community_members (community_id, role);

create index community_post_links_feed_idx
  on public.community_post_links (community_id, created_at desc);

create index community_bans_community_user_idx
  on public.community_bans (community_id, user_id);

create index reports_target_idx on public.reports (target_type, target_id);
create index reports_status_created_idx on public.reports (status, created_at desc);

create trigger communities_set_updated_at
before update on public.communities
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Internal helper functions
-- ---------------------------------------------------------------------------
-- security definer, exactly like blocked_between() / is_conversation_member(),
-- so they can be used inside RLS policies and RPCs without recursion or an
-- extra client-facing grant on community_members / community_bans.

-- The caller's role in a community, or null if not a member.
create function public.community_role(p_community_id bigint, p_user_id uuid)
returns text
language sql
security definer
stable
set search_path = ''
as $$
  select role from public.community_members
  where community_id = p_community_id and user_id = p_user_id;
$$;

create function public.is_community_banned(p_community_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.community_bans
    where community_id = p_community_id and user_id = p_user_id
  );
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.communities enable row level security;
alter table public.community_members enable row level security;
alter table public.community_post_links enable row level security;
alter table public.community_bans enable row level security;
alter table public.reports enable row level security;

revoke all on public.communities from anon, authenticated;
revoke all on public.community_members from anon, authenticated;
revoke all on public.community_post_links from anon, authenticated;
revoke all on public.community_bans from anon, authenticated;
revoke all on public.reports from anon, authenticated;

-- Reads only, and only where a browser should ever see the row directly. All
-- writes go through a SECURITY DEFINER RPC below, matching the Pass 1–4
-- RPC-only model. community_bans and reports get NO select grant at all —
-- every read of those two tables happens inside a SECURITY DEFINER function
-- running as the function owner (bypassing RLS), exactly how
-- blocked_between() reads public.blocks today. This is what keeps a
-- moderator's ban list and report queue from ever needing a client-readable
-- policy, and keeps "browse other users' reports" impossible for anyone.
grant select on public.communities to authenticated;
grant select on public.community_members to authenticated;
grant select on public.community_post_links to authenticated;

-- Communities are PUBLIC in V1: any authenticated row is readable while active.
create policy "Read active communities"
on public.communities for select
to authenticated
using (is_active);

-- Member lists are public alongside their (active) community.
create policy "Read members of active communities"
on public.community_members for select
to authenticated
using (
  exists (
    select 1 from public.communities c
    where c.id = community_id and c.is_active
  )
);

-- A live (not removed) link on an active community is readable directly;
-- moderators see removed links through the dedicated moderation RPC instead
-- (SECURITY DEFINER, bypasses this policy), so removed posts do not need to
-- be exposed here.
create policy "Read live community post links"
on public.community_post_links for select
to authenticated
using (
  removed_at is null
  and exists (
    select 1 from public.communities c
    where c.id = community_id and c.is_active
  )
);

-- ---------------------------------------------------------------------------
-- Mutations — communities, membership, moderation
-- ---------------------------------------------------------------------------

-- Creates a community and inserts the creator as its owner member, atomically.
-- owner_id is always auth.uid() — never a client-supplied column.
create function public.create_community(
  p_name text,
  p_slug text,
  p_description text default '',
  p_rules text default ''
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_name text := btrim(coalesce(p_name, ''));
  v_slug text := lower(btrim(coalesce(p_slug, '')));
  v_description text := btrim(coalesce(p_description, ''));
  v_rules text := btrim(coalesce(p_rules, ''));
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.profiles where id = v_viewer and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  if char_length(v_name) < 2 or char_length(v_name) > 80 then
    raise exception using errcode = '22023', message = 'Choose a name between 2 and 80 characters.';
  end if;

  if v_slug !~ '^[a-z0-9]+(-[a-z0-9]+)*$' or char_length(v_slug) < 3 or char_length(v_slug) > 60 then
    raise exception using errcode = '22023', message = 'Choose a valid slug.';
  end if;

  if char_length(v_description) > 2000 then
    raise exception using errcode = '22023', message = 'Description must be 2000 characters or fewer.';
  end if;

  if char_length(v_rules) > 5000 then
    raise exception using errcode = '22023', message = 'Rules must be 5000 characters or fewer.';
  end if;

  if exists (select 1 from public.communities where slug = v_slug) then
    raise exception using errcode = '23505', message = 'That slug is already taken.';
  end if;

  insert into public.communities (owner_id, slug, name, description, rules)
  values (v_viewer, v_slug, v_name, v_description, v_rules)
  returning id into v_new_id;

  insert into public.community_members (community_id, user_id, role)
  values (v_new_id, v_viewer, 'owner');

  return v_new_id;
end;
$$;

-- Join an active community. Idempotent (on conflict do nothing). Rejects a
-- banned caller before checking existing membership.
create function public.join_community(p_community_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.profiles where id = v_viewer and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and is_active
  ) then
    raise exception using errcode = '42501', message = 'This community is not available.';
  end if;

  if public.is_community_banned(p_community_id, v_viewer) then
    raise exception using errcode = '42501', message = 'You cannot join this community.';
  end if;

  insert into public.community_members (community_id, user_id, role)
  values (p_community_id, v_viewer, 'member')
  on conflict (community_id, user_id) do nothing;
end;
$$;

-- Leave a community. A no-op (not an error) for a caller who is not a
-- member. The owner can never leave in V1 (no ownership transfer) — this is
-- rejected with a safe, specific message rather than the generic
-- not_available case.
create function public.leave_community(p_community_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if exists (
    select 1 from public.communities where id = p_community_id and owner_id = v_viewer
  ) then
    raise exception using errcode = '42501',
      message = 'Community owners cannot leave their community.';
  end if;

  delete from public.community_members
  where community_id = p_community_id and user_id = v_viewer;
end;
$$;

-- Creates a normal Diong post (always visibility = 'public') and links it to
-- the community in one atomic function body. Requires live membership, no
-- ban, and an active community — re-checked here even though join_community
-- already screens membership, since a ban can be applied after joining.
create function public.create_community_post(
  p_community_id bigint,
  p_post_type text,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
  v_post_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and is_active
  ) then
    raise exception using errcode = '42501', message = 'This community is not available.';
  end if;

  if public.is_community_banned(p_community_id, v_viewer) then
    raise exception using errcode = '42501', message = 'You cannot post in this community.';
  end if;

  if public.community_role(p_community_id, v_viewer) is null then
    raise exception using errcode = '42501', message = 'Join this community to post.';
  end if;

  if p_post_type is null or p_post_type not in (
    'update', 'reflection', 'progress', 'learning', 'achievement', 'question', 'resource'
  ) then
    raise exception using errcode = '22023', message = 'Choose a valid post type.';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 5000 then
    raise exception using errcode = '22023', message = 'Write between 1 and 5000 characters.';
  end if;

  insert into public.posts (user_id, post_type, body, visibility)
  values (v_viewer, p_post_type, v_body, 'public')
  returning id into v_post_id;

  insert into public.community_post_links (community_id, post_id, author_id)
  values (p_community_id, v_post_id, v_viewer);

  return v_post_id;
end;
$$;

-- Removes a post FROM THE COMMUNITY only: stamps the link row. The
-- underlying public.posts row is never modified or deleted here, so the
-- author's post keeps its normal Diong visibility. Owner or moderator only.
create function public.remove_community_post(
  p_community_id bigint,
  p_post_id bigint,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
  v_role text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  v_role := public.community_role(p_community_id, v_viewer);
  -- coalesce is required: for a non-member v_role is NULL, and "NULL not in
  -- (...)" evaluates to NULL, which PL/pgSQL's IF treats as false (branch
  -- skipped) — without the coalesce a non-member would silently bypass this
  -- authorization check entirely.
  if coalesce(v_role, 'none') not in ('owner', 'moderator') then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  if v_reason is not null and char_length(v_reason) > 500 then
    raise exception using errcode = '22023', message = 'Reason must be 500 characters or fewer.';
  end if;

  update public.community_post_links
  set removed_at = now(), removed_by = v_viewer, removal_reason = v_reason
  where community_id = p_community_id and post_id = p_post_id and removed_at is null;

  if not found then
    raise exception using errcode = '42501', message = 'This community post is not available.';
  end if;
end;
$$;

-- Owner-only. Promotes an existing plain member to moderator. Never operates
-- on the owner (who already holds 'owner' and is excluded by the role check).
create function public.promote_community_moderator(p_community_id bigint, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and owner_id = v_viewer
  ) then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  update public.community_members
  set role = 'moderator'
  where community_id = p_community_id and user_id = p_user_id and role = 'member';

  if not found then
    raise exception using errcode = '42501', message = 'That member is not available.';
  end if;
end;
$$;

-- Owner-only. Demotes an existing moderator back to plain member.
create function public.demote_community_moderator(p_community_id bigint, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and owner_id = v_viewer
  ) then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  update public.community_members
  set role = 'member'
  where community_id = p_community_id and user_id = p_user_id and role = 'moderator';

  if not found then
    raise exception using errcode = '42501', message = 'That moderator is not available.';
  end if;
end;
$$;

-- Owner or moderator. Neither may ever target the owner. A moderator may
-- only remove a plain member — never another moderator; only the owner
-- manages moderators (promote/demote/remove).
create function public.remove_community_member(p_community_id bigint, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_caller_role text;
  v_target_role text;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  v_caller_role := public.community_role(p_community_id, v_viewer);
  -- coalesce guards against PL/pgSQL treating "NULL not in (...)" as false
  -- (branch skipped) for a caller who is not a member at all.
  if coalesce(v_caller_role, 'none') not in ('owner', 'moderator') then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  v_target_role := public.community_role(p_community_id, p_user_id);
  if v_target_role is null then
    raise exception using errcode = '42501', message = 'That member is not available.';
  end if;
  if v_target_role = 'owner' then
    raise exception using errcode = '42501', message = 'The owner cannot be removed.';
  end if;
  if v_caller_role = 'moderator' and v_target_role = 'moderator' then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  delete from public.community_members
  where community_id = p_community_id and user_id = p_user_id;
end;
$$;

-- Owner or moderator. Same never-the-owner / moderator-cannot-target-moderator
-- rule as remove_community_member. Removes membership and records the ban.
create function public.ban_community_member(
  p_community_id bigint,
  p_user_id uuid,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_caller_role text;
  v_target_role text;
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  v_caller_role := public.community_role(p_community_id, v_viewer);
  -- coalesce guards against PL/pgSQL treating "NULL not in (...)" as false
  -- (branch skipped) for a caller who is not a member at all.
  if coalesce(v_caller_role, 'none') not in ('owner', 'moderator') then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  v_target_role := public.community_role(p_community_id, p_user_id);
  if v_target_role = 'owner' then
    raise exception using errcode = '42501', message = 'The owner cannot be banned.';
  end if;
  if v_caller_role = 'moderator' and v_target_role = 'moderator' then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  if v_reason is not null and char_length(v_reason) > 500 then
    raise exception using errcode = '22023', message = 'Reason must be 500 characters or fewer.';
  end if;

  delete from public.community_members
  where community_id = p_community_id and user_id = p_user_id;

  insert into public.community_bans (community_id, user_id, banned_by, reason)
  values (p_community_id, p_user_id, v_viewer, v_reason)
  on conflict (community_id, user_id) do nothing;
end;
$$;

-- Owner or moderator. Unbanning does NOT recreate membership — the user may
-- join again through the normal join_community path.
create function public.unban_community_member(p_community_id bigint, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  -- coalesce guards against PL/pgSQL treating "NULL not in (...)" as false
  -- (branch skipped) for a caller who is not a member at all.
  if coalesce(public.community_role(p_community_id, v_viewer), 'none')
      not in ('owner', 'moderator') then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  delete from public.community_bans
  where community_id = p_community_id and user_id = p_user_id;
end;
$$;

-- Creates a report. reporter_id is always auth.uid(). Silently succeeds (no
-- new row, no error) on a duplicate open report against the same target, so
-- the caller never learns whether their report was the first — the same
-- "never reveal what moderation will do" policy the brief asks for.
create function public.create_report(
  p_target_type text,
  p_target_id bigint,
  p_target_user_id uuid,
  p_reason text,
  p_details text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_details text := nullif(btrim(coalesce(p_details, '')), '');
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.profiles where id = v_viewer and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  if p_target_type is null or p_target_type not in (
    'post', 'comment', 'profile', 'community', 'community_post'
  ) then
    raise exception using errcode = '22023', message = 'Choose a valid report target.';
  end if;

  if p_reason is null or p_reason not in (
    'spam', 'harassment', 'hate_or_abuse', 'unsafe_content',
    'misinformation', 'impersonation', 'other'
  ) then
    raise exception using errcode = '22023', message = 'Choose a valid reason.';
  end if;

  if v_details is not null and char_length(v_details) > 2000 then
    raise exception using errcode = '22023', message = 'Details must be 2000 characters or fewer.';
  end if;

  if p_target_type = 'profile' then
    if p_target_user_id is null or p_target_id is not null then
      raise exception using errcode = '22023', message = 'Choose a valid report target.';
    end if;
    if p_target_user_id = v_viewer then
      raise exception using errcode = '22023', message = 'You cannot report your own profile.';
    end if;
    if not exists (
      select 1 from public.profiles where id = p_target_user_id and onboarding_completed
    ) then
      raise exception using errcode = '42501', message = 'This account is not available.';
    end if;
  else
    if p_target_id is null or p_target_user_id is not null then
      raise exception using errcode = '22023', message = 'Choose a valid report target.';
    end if;

    if p_target_type = 'post' and not public.viewer_can_see_post(p_target_id) then
      raise exception using errcode = '42501', message = 'This post is not available.';
    end if;

    if p_target_type = 'comment' and not exists (
      select 1 from public.post_comments c
      where c.id = p_target_id
        and c.deleted_at is null
        and public.viewer_can_see_post(c.post_id)
    ) then
      raise exception using errcode = '42501', message = 'This comment is not available.';
    end if;

    if p_target_type = 'community' and not exists (
      select 1 from public.communities where id = p_target_id and is_active
    ) then
      raise exception using errcode = '42501', message = 'This community is not available.';
    end if;

    if p_target_type = 'community_post' and not exists (
      select 1 from public.community_post_links l
      join public.communities c on c.id = l.community_id
      where l.post_id = p_target_id and l.removed_at is null and c.is_active
    ) then
      raise exception using errcode = '42501', message = 'This community post is not available.';
    end if;
  end if;

  insert into public.reports
    (reporter_id, target_type, target_id, target_user_id, reason, details)
  values
    (v_viewer, p_target_type, p_target_id, p_target_user_id, p_reason, v_details)
  on conflict (
    reporter_id, target_type, coalesce(target_id, -1),
    coalesce(target_user_id, '00000000-0000-0000-0000-000000000000'::uuid)
  )
  where status = 'open'
  do nothing;
end;
$$;

-- ---------------------------------------------------------------------------
-- Read RPCs
-- ---------------------------------------------------------------------------

-- One community from the viewer's point of view, or no row when missing /
-- inactive. Resolves the viewer's role (null when not a member) and a live
-- member count.
create function public.get_community(p_slug text)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  rules text,
  owner_id uuid,
  owner_username text,
  owner_display_name text,
  member_count integer,
  created_at timestamptz,
  viewer_role text
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    c.rules,
    c.owner_id,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.community_members m where m.community_id = c.id),
    c.created_at,
    public.community_role(c.id, v_viewer)
  from public.communities c
  join public.profiles pr on pr.id = c.owner_id
  where c.slug = lower(btrim(coalesce(p_slug, '')))
    and c.is_active;
end;
$$;

-- Communities the viewer has joined (any role), alphabetical by name — a
-- deterministic order with id as the final tie-break, offset paginated.
create function public.list_my_communities(
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  member_count integer,
  viewer_role text,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    (select count(*)::integer from public.community_members m2 where m2.community_id = c.id),
    cm.role,
    count(*) over ()
  from public.community_members cm
  join public.communities c on c.id = cm.community_id and c.is_active
  where cm.user_id = v_viewer
  order by c.name asc, c.id asc
  limit v_limit offset v_offset;
end;
$$;

-- Active communities the viewer has not joined and is not banned from,
-- newest first, id as the final tie-break, offset paginated.
create function public.list_discover_communities(
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  member_count integer,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    (select count(*)::integer from public.community_members m where m.community_id = c.id),
    count(*) over ()
  from public.communities c
  where c.is_active
    and not exists (
      select 1 from public.community_members m
      where m.community_id = c.id and m.user_id = v_viewer
    )
    and not public.is_community_banned(c.id, v_viewer)
  order by c.created_at desc, c.id desc
  limit v_limit offset v_offset;
end;
$$;

-- Case-insensitive substring match against name / slug / description, active
-- communities only. Same page-with-total shape as search_people().
create function public.search_communities(
  p_query text,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id bigint,
  slug text,
  name text,
  description text,
  member_count integer,
  viewer_joined boolean,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_query text := btrim(coalesce(p_query, ''));
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_query) < 2 then
    return;
  end if;

  return query
  select
    c.id,
    c.slug,
    c.name,
    c.description,
    (select count(*)::integer from public.community_members m2 where m2.community_id = c.id),
    exists (
      select 1 from public.community_members m3
      where m3.community_id = c.id and m3.user_id = v_viewer
    ),
    count(*) over ()
  from public.communities c
  where c.is_active
    and (
      c.name ilike '%' || v_query || '%'
      or c.slug ilike '%' || v_query || '%'
      or c.description ilike '%' || v_query || '%'
    )
  order by (c.name ilike v_query || '%') desc, c.name asc, c.id asc
  limit v_limit offset v_offset;
end;
$$;

-- Members of a community, grouped by role rank (owner, moderator, member)
-- then join order, block-filtered, offset paginated. Only public profile
-- fields are returned — never email or auth metadata.
create function public.list_community_members(
  p_community_id bigint,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  user_id uuid,
  username text,
  display_name text,
  role text,
  joined_at timestamptz,
  total_count bigint
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.communities where id = p_community_id and is_active
  ) then
    return;
  end if;

  return query
  select
    m.user_id,
    pr.username,
    pr.display_name,
    m.role,
    m.joined_at,
    count(*) over ()
  from public.community_members m
  join public.profiles pr on pr.id = m.user_id
  where m.community_id = p_community_id
    and not public.blocked_between(v_viewer, m.user_id)
  order by
    case m.role when 'owner' then 0 when 'moderator' then 1 else 2 end,
    m.joined_at asc,
    m.user_id asc
  limit v_limit offset v_offset;
end;
$$;

-- Posts in a community, newest first, block-filtered, keyset paginated on
-- (created_at, id) — identical row shape to list_feed() / list_discover_posts()
-- / search_posts() so the application layer reuses the same mapping and
-- components. Only live (not removed) links on live (not deleted) posts.
create function public.list_community_posts(
  p_community_id bigint,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer
  from public.community_post_links l
  join public.posts p on p.id = l.post_id
  join public.profiles pr on pr.id = p.user_id
  where l.community_id = p_community_id
    and l.removed_at is null
    and p.deleted_at is null
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- Reports connected to one community: reports on the community itself, and
-- reports on any of its (not-removed) community posts. Owner/moderator only.
-- Never returns reporter_id — reporter identity is never exposed, even to
-- community moderators.
create function public.list_community_moderation_reports(p_community_id bigint)
returns table (
  id bigint,
  target_type text,
  target_id bigint,
  reason text,
  details text,
  status text,
  created_at timestamptz
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  -- coalesce guards against PL/pgSQL treating "NULL not in (...)" as false
  -- (branch skipped) for a caller who is not a member at all.
  if coalesce(public.community_role(p_community_id, v_viewer), 'none')
      not in ('owner', 'moderator') then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  return query
  select r.id, r.target_type, r.target_id, r.reason, r.details, r.status, r.created_at
  from public.reports r
  where
    (r.target_type = 'community' and r.target_id = p_community_id)
    or (
      r.target_type = 'community_post'
      and exists (
        select 1 from public.community_post_links l
        where l.community_id = p_community_id and l.post_id = r.target_id
      )
    )
  order by r.created_at desc, r.id desc
  limit 200;
end;
$$;

-- Banned users for one community (owner/moderator only) — lets a moderator
-- find who to unban. Only public profile fields; never selects community_bans
-- directly from the client (no select grant exists on that table at all).
create function public.list_community_bans(p_community_id bigint)
returns table (
  user_id uuid,
  username text,
  display_name text,
  reason text,
  created_at timestamptz
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  -- coalesce guards against PL/pgSQL treating "NULL not in (...)" as false
  -- (branch skipped) for a caller who is not a member at all.
  if coalesce(public.community_role(p_community_id, v_viewer), 'none')
      not in ('owner', 'moderator') then
    raise exception using errcode = '42501', message = 'You are not authorized to do that.';
  end if;

  return query
  select b.user_id, pr.username, pr.display_name, b.reason, b.created_at
  from public.community_bans b
  join public.profiles pr on pr.id = b.user_id
  where b.community_id = p_community_id
  order by b.created_at desc
  limit 200;
end;
$$;

-- A live community link for one post, or no row when the post is not linked
-- to any (active) community. Purely additive lookup used so a post rendered
-- outside its community's own page (e.g. /posts/[id]) can still show which
-- community it belongs to, without changing the shape of the pre-existing
-- list_feed() / get_post() / list_user_posts() / list_discover_posts() /
-- search_posts() functions from earlier, already-applied migrations.
create function public.get_post_community(p_post_id bigint)
returns table (
  community_id bigint,
  slug text,
  name text
)
language sql
security definer
stable
set search_path = ''
as $$
  select c.id, c.slug, c.name
  from public.community_post_links l
  join public.communities c on c.id = l.community_id
  where l.post_id = p_post_id
    and l.removed_at is null
    and c.is_active;
$$;

-- ---------------------------------------------------------------------------
-- Execution privileges
-- ---------------------------------------------------------------------------

revoke all on function public.community_role(bigint, uuid) from public, anon;
revoke all on function public.is_community_banned(bigint, uuid) from public, anon;
revoke all on function public.create_community(text, text, text, text) from public, anon;
revoke all on function public.join_community(bigint) from public, anon;
revoke all on function public.leave_community(bigint) from public, anon;
revoke all on function public.create_community_post(bigint, text, text) from public, anon;
revoke all on function public.remove_community_post(bigint, bigint, text) from public, anon;
revoke all on function public.promote_community_moderator(bigint, uuid) from public, anon;
revoke all on function public.demote_community_moderator(bigint, uuid) from public, anon;
revoke all on function public.remove_community_member(bigint, uuid) from public, anon;
revoke all on function public.ban_community_member(bigint, uuid, text) from public, anon;
revoke all on function public.unban_community_member(bigint, uuid) from public, anon;
revoke all on function public.create_report(text, bigint, uuid, text, text) from public, anon;
revoke all on function public.get_community(text) from public, anon;
revoke all on function public.list_my_communities(integer, integer) from public, anon;
revoke all on function public.list_discover_communities(integer, integer) from public, anon;
revoke all on function public.search_communities(text, integer, integer) from public, anon;
revoke all on function public.list_community_members(bigint, integer, integer) from public, anon;
revoke all on function public.list_community_posts(bigint, timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_community_moderation_reports(bigint) from public, anon;
revoke all on function public.list_community_bans(bigint) from public, anon;
revoke all on function public.get_post_community(bigint) from public, anon;

grant execute on function public.community_role(bigint, uuid) to authenticated;
grant execute on function public.is_community_banned(bigint, uuid) to authenticated;
grant execute on function public.create_community(text, text, text, text) to authenticated;
grant execute on function public.join_community(bigint) to authenticated;
grant execute on function public.leave_community(bigint) to authenticated;
grant execute on function public.create_community_post(bigint, text, text) to authenticated;
grant execute on function public.remove_community_post(bigint, bigint, text) to authenticated;
grant execute on function public.promote_community_moderator(bigint, uuid) to authenticated;
grant execute on function public.demote_community_moderator(bigint, uuid) to authenticated;
grant execute on function public.remove_community_member(bigint, uuid) to authenticated;
grant execute on function public.ban_community_member(bigint, uuid, text) to authenticated;
grant execute on function public.unban_community_member(bigint, uuid) to authenticated;
grant execute on function public.create_report(text, bigint, uuid, text, text) to authenticated;
grant execute on function public.get_community(text) to authenticated;
grant execute on function public.list_my_communities(integer, integer) to authenticated;
grant execute on function public.list_discover_communities(integer, integer) to authenticated;
grant execute on function public.search_communities(text, integer, integer) to authenticated;
grant execute on function public.list_community_members(bigint, integer, integer) to authenticated;
grant execute on function public.list_community_posts(bigint, timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_community_moderation_reports(bigint) to authenticated;
grant execute on function public.list_community_bans(bigint) to authenticated;
grant execute on function public.get_post_community(bigint) to authenticated;

commit;
