begin;

-- Diong Social Graph — Social Network Pass 1: the follow / block foundation.
--
-- Additive only. Adds two tables (public.follows, public.blocks), their RLS,
-- two integrity triggers and five SECURITY DEFINER RPCs. Nothing in this file
-- alters an existing table, function, grant, policy or trigger. Daily Prime,
-- Prime history / reflections and Connections are untouched.
--
-- Apply once, in order, after 202609100001_prime_reflections.sql. Depends only
-- on public.profiles / auth.users from 202607190001_onboarding_and_profiles.sql.
-- Each migration is a single transaction and is NOT idempotent — never re-run a
-- migration that already succeeded.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint follows_no_self_follow check (follower_id <> following_id),
  constraint follows_unique_pair unique (follower_id, following_id)
);

create table public.blocks (
  id bigint generated by default as identity primary key,
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint blocks_no_self_block check (blocker_id <> blocked_id),
  constraint blocks_unique_pair unique (blocker_id, blocked_id)
);

-- "Who does X follow" is served by the unique(follower_id, following_id) index.
-- Add the reverse index for "who follows X" and both directions for blocks.
create index follows_following_id_idx on public.follows (following_id);
create index blocks_blocker_id_idx on public.blocks (blocker_id);
create index blocks_blocked_id_idx on public.blocks (blocked_id);

-- ---------------------------------------------------------------------------
-- Integrity triggers (defence in depth)
-- ---------------------------------------------------------------------------
-- The RPCs below are the only write path in the application, but these triggers
-- keep the follow/block invariants true no matter how a row is inserted.

-- A follow edge can never coexist with a block in either direction between the
-- two users.
create function public.enforce_follow_not_blocked()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (
    select 1
    from public.blocks
    where (blocker_id = new.follower_id and blocked_id = new.following_id)
       or (blocker_id = new.following_id and blocked_id = new.follower_id)
  ) then
    raise exception using errcode = '42501',
      message = 'This account is not available.';
  end if;
  return new;
end;
$$;

create trigger follows_enforce_not_blocked
before insert on public.follows
for each row execute function public.enforce_follow_not_blocked();

-- Creating a block removes any follow edge in either direction, in the same
-- transaction as the block insert.
create function public.clear_follows_on_block()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.follows
  where (follower_id = new.blocker_id and following_id = new.blocked_id)
     or (follower_id = new.blocked_id and following_id = new.blocker_id);
  return new;
end;
$$;

create trigger blocks_clear_mutual_follow
after insert on public.blocks
for each row execute function public.clear_follows_on_block();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.follows enable row level security;
alter table public.blocks enable row level security;

revoke all on public.follows from anon, authenticated;
revoke all on public.blocks from anon, authenticated;

-- Reads only. Every write goes through a SECURITY DEFINER RPC below, matching
-- the connection_interactions RPC-only model.
grant select on public.follows to authenticated;
grant select on public.blocks to authenticated;

-- follows: the follow graph (who follows whom, and the counts derived from it)
-- is visible to any signed-in user. Block-aware privacy is enforced at the
-- profile boundary by public.get_social_profile(): a viewer the owner has
-- blocked cannot resolve the owner's profile and the app will not render the
-- owner's follower / following lists for that viewer.
create policy "Authenticated users can read the follow graph"
on public.follows for select
to authenticated
using (true);

-- blocks: a user can read only the blocks they created. "Who has blocked me" is
-- never directly readable by a client; it is applied server-side inside the
-- RPCs.
create policy "Users can read their own blocks"
on public.blocks for select
to authenticated
using ((select auth.uid()) = blocker_id);

-- ---------------------------------------------------------------------------
-- Mutations — the only write path for follows and blocks
-- ---------------------------------------------------------------------------

-- follow_user: the caller follows p_target_id. Caller is auth.uid(); the target
-- is never trusted from a client-supplied user_id column.
create function public.follow_user(p_target_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if p_target_id is null or p_target_id = current_user_id then
    raise exception using errcode = '22023', message = 'You cannot follow this account.';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_target_id and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  if exists (
    select 1 from public.blocks
    where (blocker_id = current_user_id and blocked_id = p_target_id)
       or (blocker_id = p_target_id and blocked_id = current_user_id)
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  insert into public.follows (follower_id, following_id)
  values (current_user_id, p_target_id)
  on conflict (follower_id, following_id) do nothing;
end;
$$;

-- unfollow_user: the caller stops following p_target_id. Idempotent.
create function public.unfollow_user(p_target_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  delete from public.follows
  where follower_id = current_user_id
    and following_id = p_target_id;
end;
$$;

-- block_user: the caller blocks p_target_id. The blocks_clear_mutual_follow
-- trigger removes both follow edges in the same transaction. Idempotent.
create function public.block_user(p_target_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if p_target_id is null or p_target_id = current_user_id then
    raise exception using errcode = '22023', message = 'You cannot block this account.';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_target_id and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  insert into public.blocks (blocker_id, blocked_id)
  values (current_user_id, p_target_id)
  on conflict (blocker_id, blocked_id) do nothing;
end;
$$;

-- unblock_user: the caller removes their block on p_target_id. Idempotent. Does
-- not restore any follow edge that was cleared when the block was created.
create function public.unblock_user(p_target_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  delete from public.blocks
  where blocker_id = current_user_id
    and blocked_id = p_target_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- get_social_profile — the block-aware public profile read
-- ---------------------------------------------------------------------------
-- Resolves a username to its completed-onboarding profile and returns the
-- viewer-relative social state in one call. Deterministic and read-only.
--
--   * Returns NO ROW when the username does not resolve, OR when the profile
--     owner has blocked the viewer. The caller treats "no row" as notFound(),
--     so a blocked viewer cannot tell a blocking profile from a missing one.
--   * When the viewer has blocked the owner, the row is returned with
--     viewer_blocked = true and bio / follower_count / following_count nulled,
--     so the caller can render a restrained "you blocked this account" state.
--   * follower_count / following_count are computed here (SECURITY DEFINER), so
--     they are correct regardless of the follows RLS policy.
create function public.get_social_profile(p_username text)
returns table (
  id uuid,
  username text,
  display_name text,
  bio text,
  follower_count integer,
  following_count integer,
  is_self boolean,
  viewer_follows boolean,
  viewer_blocked boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  normalized text := lower(btrim(coalesce(p_username, '')));
  target public.profiles;
  v_is_self boolean;
  v_blocked_by boolean;
  v_viewer_blocked boolean;
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if normalized !~ '^[a-z0-9_]{3,30}$' then
    return;
  end if;

  select * into target
  from public.profiles
  where username = normalized
    and onboarding_completed;

  if not found then
    return;
  end if;

  v_is_self := target.id = current_user_id;

  v_blocked_by := (not v_is_self) and exists (
    select 1 from public.blocks
    where blocker_id = target.id and blocked_id = current_user_id
  );
  if v_blocked_by then
    return;
  end if;

  v_viewer_blocked := (not v_is_self) and exists (
    select 1 from public.blocks
    where blocker_id = current_user_id and blocked_id = target.id
  );

  return query
  select
    target.id,
    target.username,
    target.display_name,
    case when v_viewer_blocked then null else target.bio end,
    case
      when v_viewer_blocked then null
      else (select count(*)::integer from public.follows where following_id = target.id)
    end,
    case
      when v_viewer_blocked then null
      else (select count(*)::integer from public.follows where follower_id = target.id)
    end,
    v_is_self,
    (not v_is_self) and exists (
      select 1 from public.follows
      where follower_id = current_user_id and following_id = target.id
    ),
    v_viewer_blocked;
end;
$$;

-- ---------------------------------------------------------------------------
-- Execution privileges
-- ---------------------------------------------------------------------------

revoke all on function public.follow_user(uuid) from public, anon;
revoke all on function public.unfollow_user(uuid) from public, anon;
revoke all on function public.block_user(uuid) from public, anon;
revoke all on function public.unblock_user(uuid) from public, anon;
revoke all on function public.get_social_profile(text) from public, anon;

grant execute on function public.follow_user(uuid) to authenticated;
grant execute on function public.unfollow_user(uuid) to authenticated;
grant execute on function public.block_user(uuid) to authenticated;
grant execute on function public.unblock_user(uuid) to authenticated;
grant execute on function public.get_social_profile(text) to authenticated;

-- Trigger functions are invoked only by their triggers, never called directly.
revoke all on function public.enforce_follow_not_blocked() from public, anon, authenticated;
revoke all on function public.clear_follows_on_block() from public, anon, authenticated;

commit;
