begin;

create table public.prime_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  description text,
  interest_id bigint references public.interests(id) on delete set null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint prime_categories_slug_format
    check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint prime_categories_name_length
    check (char_length(btrim(name)) between 1 and 60)
);

create table public.prime_protocols (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.prime_categories(id) on delete restrict,
  slug text not null unique,
  title text not null,
  purpose text,
  best_time text,
  prime_text text not null,
  action_trigger text not null,
  tomorrows_expectation text,
  reflection_prompt text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prime_protocols_status check (status in ('draft', 'published', 'archived')),
  constraint prime_protocols_slug_format
    check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint prime_protocols_title_length
    check (char_length(btrim(title)) between 1 and 120),
  constraint prime_protocols_prime_text_length
    check (char_length(btrim(prime_text)) between 1 and 1200),
  constraint prime_protocols_action_trigger_length
    check (char_length(btrim(action_trigger)) between 1 and 500)
);

create table public.prime_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prime_protocol_id bigint not null references public.prime_protocols(id) on delete restrict,
  assigned_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (user_id, assigned_date)
);

create table public.prime_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prime_assignment_id bigint not null references public.prime_assignments(id) on delete cascade,
  completion_date date not null default current_date,
  completed_at timestamptz not null default now(),
  note text,
  unique (user_id, prime_assignment_id),
  constraint prime_completions_note_length
    check (note is null or char_length(note) <= 500)
);

create index prime_categories_interest_id_idx on public.prime_categories (interest_id);
create index prime_protocols_category_status_idx on public.prime_protocols (category_id, status);
create index prime_assignments_user_date_idx on public.prime_assignments (user_id, assigned_date desc);
create index prime_completions_user_date_idx on public.prime_completions (user_id, completion_date desc);

create trigger prime_protocols_set_updated_at
before update on public.prime_protocols
for each row execute function public.set_updated_at();

insert into public.prime_categories (slug, name, description, interest_id, sort_order)
select seed.slug, seed.name, seed.description, interests.id, seed.sort_order
from (values
  ('consistency', 'Consistency', 'Practise reliable, repeatable action.', 'consistency', 10),
  ('focus', 'Focus', 'Direct attention toward what matters now.', 'focus', 20),
  ('confidence', 'Confidence', 'Build self-trust through purposeful action.', 'confidence', 30),
  ('productivity', 'Productivity', 'Make useful progress with clear priorities.', 'productivity', 40),
  ('goal-achievement', 'Goal Achievement', 'Turn meaningful aims into manageable steps.', 'goal-achievement', 50),
  ('learning', 'Learning', 'Approach knowledge and skills with intention.', 'learning', 60),
  ('career-growth', 'Career Growth', 'Take thoughtful steps in working life.', 'career-growth', 70),
  ('creativity', 'Creativity', 'Make room for ideas and creative practice.', 'creativity', 80),
  ('wellbeing', 'Health and Wellbeing', 'Support balanced everyday choices.', 'health-and-wellbeing', 90),
  ('relationships', 'Relationships', 'Bring attention and care to relationships.', 'relationships', 100),
  ('financial-growth', 'Financial Growth', 'Practise intentional financial habits.', 'financial-growth', 110),
  ('recovery', 'Sleep and Recovery', 'Make room for rest and sustainable routines.', 'sleep-and-recovery', 120)
) as seed(slug, name, description, interest_slug, sort_order)
join public.interests on interests.slug = seed.interest_slug
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    interest_id = excluded.interest_id,
    sort_order = excluded.sort_order;

insert into public.prime_protocols (
  category_id, slug, title, purpose, best_time, prime_text, action_trigger,
  tomorrows_expectation, reflection_prompt, status
)
select categories.id, seed.slug, seed.title, seed.purpose, seed.best_time,
  seed.prime_text, seed.action_trigger, seed.expectation, seed.reflection, 'published'
from (values
  ('consistency', 'show-up-small', 'Show Up Small', 'Make consistency easier by lowering the starting threshold.', 'At the start of your day.',
   'Consistency grows through actions you can repeat. A modest step completed today matters more than an ambitious plan postponed. Let the first action be small enough to begin and meaningful enough to count.',
   'Choose one useful task and work on it for ten uninterrupted minutes.',
   'Starting can feel more familiar because you practised beginning today.',
   'What helped you begin, even if you did not feel fully ready?'),
  ('consistency', 'keep-one-promise', 'Keep One Promise', 'Strengthen self-trust with one realistic commitment.', 'Morning or when planning your day.',
   'A dependable day does not require doing everything. It begins with choosing one promise that fits your time and energy, then treating that promise with care.',
   'Write down one achievable promise for today and complete it before the day ends.',
   'You will have evidence that a clear, realistic commitment can guide your action.',
   'How did keeping one promise affect the way you viewed your day?'),
  ('focus', 'one-clear-priority', 'One Clear Priority', 'Reduce competing demands by naming what matters most.', 'Before beginning focused work.',
   'Attention becomes more useful when it has a clear destination. You can acknowledge everything asking for your time without giving everything equal priority.',
   'Name today''s single most important outcome and place it at the top of your task list.',
   'Your next planning session can begin with a clearer sense of priority.',
   'What became easier after you chose one priority?'),
  ('focus', 'close-the-tabs', 'Close the Tabs', 'Create a calmer environment for sustained attention.', 'Immediately before a concentration block.',
   'Your environment can support the attention you want to give. Removing a few visible distractions is a practical way to make the intended action easier to return to.',
   'Close unrelated tabs, silence non-essential alerts and focus on one task for fifteen minutes.',
   'A prepared workspace can make the next focus block simpler to begin.',
   'Which distraction was most useful to remove?'),
  ('confidence', 'evidence-of-capability', 'Evidence of Capability', 'Notice concrete evidence of skills you already use.', 'Before a demanding task.',
   'Confidence need not begin as a feeling. It can begin with honest evidence: efforts you made, skills you practised and situations you handled with care.',
   'List three specific examples of something you learned, handled or completed.',
   'You can approach tomorrow with a more balanced record of your capability.',
   'Which example felt most relevant to what you are facing now?'),
  ('confidence', 'take-the-visible-step', 'Take the Visible Step', 'Build self-trust by acting before certainty arrives.', 'When hesitation is delaying a useful action.',
   'You can act thoughtfully without waiting to feel completely certain. A small visible step creates information and gives your intention a practical form.',
   'Take one low-risk step you have been postponing, such as sending a draft or asking a clear question.',
   'The next step may be easier to judge because you created movement today.',
   'What did action teach you that thinking alone could not?'),
  ('productivity', 'define-done', 'Define Done', 'Give a task a clear and realistic finish line.', 'While planning a work session.',
   'Vague tasks expand. A useful definition of done turns effort into a specific outcome and helps you recognise when enough has been completed for today.',
   'Rewrite one vague task as a concrete result you can finish today.',
   'You can plan with clearer boundaries and less uncertainty.',
   'How did a clear finish line change your approach?'),
  ('productivity', 'two-minute-reset', 'Two-Minute Reset', 'Restore order with one brief practical action.', 'Between tasks or after an interruption.',
   'A reset does not need to become a project. One short action can reduce friction and help you enter the next part of the day with intention.',
   'Spend two minutes clearing your workspace and writing the next action in plain language.',
   'Your next session can begin with less setup and a visible starting point.',
   'What small piece of order made the biggest difference?'),
  ('goal-achievement', 'next-milestone', 'Name the Next Milestone', 'Translate a broad goal into a nearer result.', 'During weekly or daily planning.',
   'A meaningful goal becomes workable when you can see the next marker of progress. You do not need the entire route; you need a direction and the next reachable point.',
   'Write one milestone you can reach within the next seven days and its first action.',
   'Tomorrow''s choices can connect to a specific near-term result.',
   'Does this milestone feel both meaningful and manageable?'),
  ('goal-achievement', 'remove-one-obstacle', 'Remove One Obstacle', 'Make progress easier by addressing friction.', 'Before working on an important goal.',
   'Sometimes progress depends less on adding effort and more on removing an obstacle. Notice what repeatedly slows the next action, then make that action easier to start.',
   'Identify one obstacle to your goal and spend ten minutes reducing it.',
   'The next goal session can begin with less friction.',
   'Was the obstacle practical, unclear or avoidable?'),
  ('learning', 'explain-it-simply', 'Explain It Simply', 'Check understanding by putting an idea in your own words.', 'After reading, studying or practising.',
   'Understanding becomes clearer when you can express an idea without leaning on its original wording. A simple explanation reveals both what you know and what needs another look.',
   'Explain one idea you learned today in three plain-language sentences.',
   'You will have a concise explanation to revisit and refine.',
   'Which part was hardest to explain clearly?'),
  ('learning', 'curiosity-question', 'Follow One Question', 'Use curiosity to direct a focused learning session.', 'At the beginning of study.',
   'A good question gives learning a purpose. Instead of trying to absorb everything, choose one thing you genuinely want to understand and let it guide your attention.',
   'Write one specific question and spend fifteen minutes finding a reliable answer.',
   'Your next learning session can build from a question you answered or refined.',
   'What new question emerged from your search?'),
  ('career-growth', 'make-work-visible', 'Make Your Work Visible', 'Communicate useful progress with clarity.', 'Near the end of the working day.',
   'Good work benefits from clear communication. Sharing a concise update can reduce uncertainty, invite useful feedback and help others understand the progress being made.',
   'Send a brief update stating what moved forward, what is next and any genuine blocker.',
   'Tomorrow can begin with shared context and a clearer next step.',
   'What was most important for another person to understand?'),
  ('career-growth', 'skill-next-step', 'Practise the Next Skill', 'Connect career direction to deliberate practice.', 'During a planned development block.',
   'Career growth is supported by skills practised in real situations. Choose one ability relevant to where you want to go and give it a small, concrete rehearsal.',
   'Spend twenty minutes practising one career-relevant skill on a realistic example.',
   'You will have a specific practice result to review or improve.',
   'What part of the skill deserves your next practice session?'),
  ('creativity', 'ten-rough-ideas', 'Ten Rough Ideas', 'Create options without demanding early perfection.', 'At the start of creative work.',
   'Creative work needs room for unfinished possibilities. Generating several rough options helps you move past the pressure to make the first thought the final one.',
   'Write ten rough ideas without editing them until the list is complete.',
   'You will have material to sort, combine or develop.',
   'Which idea became interesting only after you kept going?'),
  ('creativity', 'make-a-small-version', 'Make a Small Version', 'Turn an idea into something you can see and assess.', 'When an idea feels too large to begin.',
   'A small version makes an idea concrete. It does not need to prove the whole concept; it only needs to reveal enough for you to learn from it.',
   'Create a rough version in twenty minutes using only what you already have.',
   'Tomorrow you can respond to something real instead of an abstract plan.',
   'What did the rough version reveal about the idea?'),
  ('wellbeing', 'supportive-pause', 'Take a Supportive Pause', 'Make space for a balanced choice during a busy day.', 'Between demanding activities.',
   'A brief pause can help you notice what the next part of the day requires. Treat the pause as practical maintenance, not something that must be earned.',
   'Step away for five minutes, drink water and decide on one supportive next action.',
   'You may enter the next task with a clearer, more deliberate choice.',
   'What did you notice once you paused?'),
  ('wellbeing', 'gentle-boundary', 'Set One Gentle Boundary', 'Protect time or energy for what matters.', 'When reviewing today''s commitments.',
   'A useful boundary can be calm and specific. It helps you make an honest choice about what you can do well instead of quietly overcommitting.',
   'Decline, defer or shorten one non-essential commitment that does not fit today.',
   'Tomorrow''s plan can reflect your actual capacity more closely.',
   'What did the boundary make room for?'),
  ('relationships', 'listen-for-meaning', 'Listen for Meaning', 'Give one conversation your full attention.', 'Before a conversation with someone important.',
   'Careful listening is an active choice. You can make room for another person''s meaning by reducing interruption and checking what you understood.',
   'In one conversation, ask a follow-up question before offering your own view.',
   'The next conversation can begin from a fuller understanding.',
   'What did you learn by staying curious a little longer?'),
  ('relationships', 'specific-appreciation', 'Offer Specific Appreciation', 'Express care through a concrete observation.', 'Any time you can contact someone meaningfully.',
   'Specific appreciation helps another person understand what you value. It moves beyond a general compliment by naming an action, quality or moment that mattered.',
   'Tell one person exactly what you appreciated and why it mattered to you.',
   'You will have strengthened a moment of connection through clear attention.',
   'How did specificity change what you wanted to say?'),
  ('financial-growth', 'review-one-number', 'Review One Number', 'Build awareness through a small financial check-in.', 'During a quiet planning moment.',
   'Financial intention begins with seeing the current picture clearly. One number reviewed without judgement can support a more informed next choice.',
   'Review one relevant number, such as a balance, bill or weekly spending total, and note one next action.',
   'Your next financial choice can begin with current information.',
   'What did the number help you decide?'),
  ('financial-growth', 'pause-before-purchase', 'Pause Before Purchase', 'Create space for an intentional spending decision.', 'Before a non-essential purchase.',
   'A pause gives you time to compare a purchase with your priorities. The aim is not automatic refusal; it is making the choice with clearer attention.',
   'Wait ten minutes before one non-essential purchase and write what value it would add.',
   'Future purchases may be easier to assess against what matters to you.',
   'Did the pause change the decision or clarify the reason?'),
  ('recovery', 'close-the-day', 'Close the Day', 'Create a simple transition away from unfinished tasks.', 'At the end of work or study.',
   'Unfinished thoughts can be placed somewhere reliable instead of carried through the evening. A short closing routine gives tomorrow a starting point and today a boundary.',
   'Write down what is unfinished and the first task for tomorrow, then close your work materials.',
   'Tomorrow can begin from a prepared note instead of a mental search.',
   'What became easier to set down once it was written?'),
  ('recovery', 'prepare-for-rest', 'Prepare for Rest', 'Support a calmer transition into your rest routine.', 'Thirty minutes before your intended bedtime.',
   'Rest is supported by the choices that surround it. A simple transition can signal that the active part of the day is ending without demanding a perfect routine.',
   'Dim one source of bright light, put one device out of reach and prepare what you need for morning.',
   'Tomorrow morning may begin with less preparation and a clearer environment.',
   'Which part of the transition felt easiest to repeat?')
) as seed(category_slug, slug, title, purpose, best_time, prime_text, action_trigger, expectation, reflection)
join public.prime_categories as categories on categories.slug = seed.category_slug
on conflict (slug) do update
set category_id = excluded.category_id,
    title = excluded.title,
    purpose = excluded.purpose,
    best_time = excluded.best_time,
    prime_text = excluded.prime_text,
    action_trigger = excluded.action_trigger,
    tomorrows_expectation = excluded.tomorrows_expectation,
    reflection_prompt = excluded.reflection_prompt,
    status = excluded.status;

alter table public.prime_categories enable row level security;
alter table public.prime_protocols enable row level security;
alter table public.prime_assignments enable row level security;
alter table public.prime_completions enable row level security;

revoke all on public.prime_categories from anon, authenticated;
revoke all on public.prime_protocols from anon, authenticated;
revoke all on public.prime_assignments from anon, authenticated;
revoke all on public.prime_completions from anon, authenticated;

grant select on public.prime_categories, public.prime_protocols,
  public.prime_assignments, public.prime_completions to authenticated;

create policy "Authenticated users can read active prime categories"
on public.prime_categories for select to authenticated using (is_active);

create policy "Authenticated users can read published prime protocols"
on public.prime_protocols for select to authenticated using (status = 'published');

create policy "Users can read their own prime assignments"
on public.prime_assignments for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their own prime completions"
on public.prime_completions for select to authenticated
using ((select auth.uid()) = user_id);

create function public.get_or_assign_daily_prime()
returns table (
  assignment_id bigint,
  assigned_date date,
  protocol_id bigint,
  category_name text,
  title text,
  purpose text,
  best_time text,
  prime_text text,
  action_trigger text,
  tomorrows_expectation text,
  reflection_prompt text,
  completed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  selected_protocol_id bigint;
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select protocols.id
  into selected_protocol_id
  from public.prime_protocols as protocols
  join public.prime_categories as categories on categories.id = protocols.category_id
  left join public.user_interests
    on user_interests.user_id = current_user_id
    and user_interests.interest_id = categories.interest_id
  where protocols.status = 'published'
    and categories.is_active
  order by
    (user_interests.interest_id is not null) desc,
    md5(current_user_id::text || current_date::text || protocols.id::text)
  limit 1;

  if selected_protocol_id is not null then
    insert into public.prime_assignments (user_id, prime_protocol_id, assigned_date)
    values (current_user_id, selected_protocol_id, current_date)
    on conflict (user_id, assigned_date) do nothing;
  end if;

  return query
  select assignments.id, assignments.assigned_date, protocols.id,
    categories.name, protocols.title, protocols.purpose, protocols.best_time,
    protocols.prime_text, protocols.action_trigger, protocols.tomorrows_expectation,
    protocols.reflection_prompt, completions.completed_at
  from public.prime_assignments as assignments
  join public.prime_protocols as protocols on protocols.id = assignments.prime_protocol_id
  join public.prime_categories as categories on categories.id = protocols.category_id
  left join public.prime_completions as completions
    on completions.prime_assignment_id = assignments.id
    and completions.user_id = current_user_id
  where assignments.user_id = current_user_id
    and assignments.assigned_date = current_date;
end;
$$;

create function public.complete_daily_prime(p_assignment_id bigint)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  completion_time timestamptz;
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.prime_assignments
    where id = p_assignment_id and user_id = current_user_id
  ) then
    raise exception using errcode = '42501', message = 'This assignment is not available.';
  end if;

  insert into public.prime_completions (
    user_id, prime_assignment_id, completion_date
  )
  select current_user_id, id, assigned_date
  from public.prime_assignments
  where id = p_assignment_id and user_id = current_user_id
  on conflict (user_id, prime_assignment_id) do update
    set completed_at = public.prime_completions.completed_at
  returning completed_at into completion_time;

  return completion_time;
end;
$$;

revoke all on function public.get_or_assign_daily_prime() from public, anon;
revoke all on function public.complete_daily_prime(bigint) from public, anon;
grant execute on function public.get_or_assign_daily_prime() to authenticated;
grant execute on function public.complete_daily_prime(bigint) to authenticated;

commit;
