begin;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  bio text,
  avatar_url text,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_required_when_complete
    check (not onboarding_completed or username is not null),
  constraint profiles_display_name_required_when_complete
    check (not onboarding_completed or display_name is not null),
  constraint profiles_username_format
    check (
      username is null or (
        username = lower(username)
        and char_length(username) between 3 and 30
        and username ~ '^[a-z0-9_]+$'
      )
    ),
  constraint profiles_display_name_length
    check (display_name is null or char_length(btrim(display_name)) between 1 and 60),
  constraint profiles_bio_length
    check (bio is null or char_length(bio) <= 300)
);

create table public.interests (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text unique not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.user_interests (
  user_id uuid not null references auth.users(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, interest_id)
);

-- The username unique constraint already supplies the username lookup index.
create index interests_active_order_idx on public.interests (sort_order, id)
  where is_active;
create index user_interests_interest_id_idx on public.user_interests (interest_id);

insert into public.interests (slug, name, description, sort_order)
values
  ('consistency', 'Consistency', 'Build steadier routines through practical, repeatable action.', 10),
  ('focus', 'Focus', 'Give your attention to what matters most right now.', 20),
  ('confidence', 'Confidence', 'Strengthen self-trust through reflection and purposeful action.', 30),
  ('productivity', 'Productivity', 'Make useful progress with clearer priorities and practical steps.', 40),
  ('goal-achievement', 'Goal Achievement', 'Turn meaningful aims into manageable next actions.', 50),
  ('learning', 'Learning', 'Develop knowledge and skills with curiosity and intention.', 60),
  ('career-growth', 'Career Growth', 'Take thoughtful steps toward a more purposeful working life.', 70),
  ('creativity', 'Creativity', 'Make space for ideas, expression and creative practice.', 80),
  ('health-and-wellbeing', 'Health and Wellbeing', 'Support balanced everyday choices and personal wellbeing.', 90),
  ('relationships', 'Relationships', 'Bring more attention and care to important relationships.', 100),
  ('financial-growth', 'Financial Growth', 'Build more intentional habits around financial goals.', 110),
  ('sleep-and-recovery', 'Sleep and Recovery', 'Make room for rest, recovery and sustainable routines.', 120)
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order;

create function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create function public.validate_profile_completion()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_count integer;
begin
  if new.onboarding_completed then
    select count(*)::integer
    into selected_count
    from public.user_interests
    join public.interests on interests.id = user_interests.interest_id
    where user_interests.user_id = new.id
      and interests.is_active;

    if selected_count not between 1 and 5 then
      raise exception using
        errcode = '23514',
        message = 'Completed onboarding requires between 1 and 5 active interests.';
    end if;
  end if;

  return new;
end;
$$;

create trigger profiles_validate_completion
before insert or update of onboarding_completed on public.profiles
for each row execute function public.validate_profile_completion();

create function public.validate_completed_user_interest_count()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  affected_user_id uuid := coalesce(new.user_id, old.user_id);
  profile_is_complete boolean;
  selected_count integer;
begin
  select onboarding_completed
  into profile_is_complete
  from public.profiles
  where id = affected_user_id;

  if profile_is_complete then
    select count(*)::integer
    into selected_count
    from public.user_interests
    join public.interests on interests.id = user_interests.interest_id
    where user_interests.user_id = affected_user_id
      and interests.is_active;

    if selected_count not between 1 and 5 then
      raise exception using
        errcode = '23514',
        message = 'Completed onboarding requires between 1 and 5 active interests.';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create constraint trigger user_interests_validate_completed_count
after insert or delete on public.user_interests
deferrable initially immediate
for each row execute function public.validate_completed_user_interest_count();

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  safe_display_name text;
begin
  safe_display_name := btrim(new.raw_user_meta_data ->> 'display_name');

  if safe_display_name is null or char_length(safe_display_name) not between 1 and 60 then
    safe_display_name := null;
  end if;

  insert into public.profiles (id, display_name)
  values (new.id, safe_display_name)
  on conflict (id) do nothing;

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Idempotently repair auth users created before this migration.
insert into public.profiles (id, display_name)
select
  users.id,
  case
    when char_length(btrim(users.raw_user_meta_data ->> 'display_name')) between 1 and 60
      then btrim(users.raw_user_meta_data ->> 'display_name')
    else null
  end
from auth.users as users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.interests enable row level security;
alter table public.user_interests enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.interests from anon, authenticated;
revoke all on public.user_interests from anon, authenticated;

grant select, insert on public.profiles to authenticated;
grant update (username, display_name, bio, avatar_url, onboarding_completed)
  on public.profiles to authenticated;
grant select on public.interests to authenticated;
grant select, insert, delete on public.user_interests to authenticated;

create policy "Authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

create policy "Users can repair their own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id and not onboarding_completed);

create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Authenticated users can read active interests"
on public.interests for select
to authenticated
using (is_active);

create policy "Users can read permitted interest selections"
on public.user_interests for select
to authenticated
using (
  (select auth.uid()) = user_id
  or exists (
    select 1
    from public.profiles
    where profiles.id = user_interests.user_id
      and profiles.onboarding_completed
  )
);

create policy "Users can add their own interest selections"
on public.user_interests for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can remove their own interest selections"
on public.user_interests for delete
to authenticated
using ((select auth.uid()) = user_id);

create function public.complete_onboarding(
  p_username text,
  p_display_name text,
  p_bio text,
  p_interest_ids bigint[]
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_username text := lower(btrim(p_username));
  clean_display_name text := btrim(p_display_name);
  clean_bio text := nullif(btrim(p_bio), '');
  selected_count integer;
  valid_count integer;
begin
  if current_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if normalized_username !~ '^[a-z0-9_]{3,30}$' then
    raise exception using errcode = '22023', message = 'Username format is invalid.';
  end if;

  if char_length(clean_display_name) not between 1 and 60 then
    raise exception using errcode = '22023', message = 'Display name length is invalid.';
  end if;

  if clean_bio is not null and char_length(clean_bio) > 300 then
    raise exception using errcode = '22023', message = 'Bio is too long.';
  end if;

  select count(distinct interest_id)::integer
  into selected_count
  from unnest(coalesce(p_interest_ids, '{}'::bigint[])) as interest_id;

  if selected_count not between 1 and 5
     or selected_count <> coalesce(array_length(p_interest_ids, 1), 0) then
    raise exception using errcode = '22023', message = 'Choose between 1 and 5 unique interests.';
  end if;

  select count(*)::integer
  into valid_count
  from public.interests
  where id = any(p_interest_ids) and is_active;

  if valid_count <> selected_count then
    raise exception using errcode = '22023', message = 'One or more interests are invalid or inactive.';
  end if;

  insert into public.profiles (id)
  values (current_user_id)
  on conflict (id) do nothing;

  update public.profiles
  set username = normalized_username,
      display_name = clean_display_name,
      bio = clean_bio,
      onboarding_completed = false
  where id = current_user_id;

  delete from public.user_interests where user_id = current_user_id;

  insert into public.user_interests (user_id, interest_id)
  select current_user_id, interest_id
  from unnest(p_interest_ids) as interest_id;

  update public.profiles
  set onboarding_completed = true
  where id = current_user_id;

  if not found then
    raise exception using errcode = 'P0001', message = 'Profile could not be completed.';
  end if;
end;
$$;

revoke all on function public.complete_onboarding(text, text, text, bigint[]) from public, anon;
grant execute on function public.complete_onboarding(text, text, text, bigint[]) to authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.validate_profile_completion() from public, anon, authenticated;
revoke all on function public.validate_completed_user_interest_count() from public, anon, authenticated;

commit;
