begin;

-- Diong Direct Messages — Social Network Pass 4.
--
-- Additive only. Adds three tables (public.conversations,
-- public.conversation_members, public.messages), their RLS, two integrity
-- triggers, one internal helper function and the SECURITY DEFINER RPCs that
-- are the only read path for the inbox / conversation / message lists and the
-- only write path for creating a conversation, sending a message and marking
-- a conversation read. It also extends (via ALTER TABLE / CREATE OR REPLACE
-- FUNCTION, never by editing an applied file) the existing
-- public.notifications table from Pass 3 with a new 'new_message'
-- notification type, and adds one AFTER INSERT trigger on the new
-- public.messages table that generates that notification from the
-- send_message() write path (no new client-writable surface). Nothing in
-- this file alters an already-applied migration file, Daily Prime, Prime
-- history / reflections, Connections, the Pass 1 follow / block graph, the
-- Pass 2 post/comment/like/bookmark semantics or the Pass 3 Discover / Search
-- read paths.
--
-- Apply once, in order, after 202609120001_fix_social_profile_username.sql.
-- Depends on public.profiles / auth.users (202607190001),
-- public.follows / public.blocks / public.blocked_between (202609100002 /
-- 202609100003) and public.notifications (202609100004). Each migration is a
-- single transaction and is NOT idempotent — never re-run a migration that
-- already succeeded.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- Exactly one direct conversation per user pair: the two participant ids are
-- always stored in canonical (smaller, larger) order, so a
-- unique(user_min_id, user_max_id) index makes a second conversation between
-- the same two accounts impossible regardless of call order — no separate
-- lookup-then-insert race is possible to get wrong.
create table public.conversations (
  id bigint generated by default as identity primary key,
  user_min_id uuid not null references auth.users(id) on delete cascade,
  user_max_id uuid not null references auth.users(id) on delete cascade,
  -- Denormalised for inbox ordering; stamped by send_message(). Null until the
  -- first message is sent — a conversation with no messages yet does not
  -- appear in list_conversations().
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  constraint conversations_ordered_pair check (user_min_id < user_max_id),
  constraint conversations_unique_pair unique (user_min_id, user_max_id)
);

create table public.conversation_members (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Everything with created_at at or before this timestamp is read; null means
  -- nothing has ever been read. Updated by send_message() (for the sender) and
  -- mark_conversation_read() (for the reader).
  last_read_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint messages_body_not_empty check (char_length(btrim(body)) between 1 and 5000)
);

create index conversations_last_message_activity_idx
  on public.conversations (last_message_at desc, id desc)
  where last_message_at is not null;

-- The (conversation_id, user_id) primary key serves "who is in conversation X".
-- Add the reverse for "which conversations is user X in" (the inbox query).
create index conversation_members_user_id_idx
  on public.conversation_members (user_id);

create index messages_conversation_created_idx
  on public.messages (conversation_id, created_at desc, id desc);

-- ---------------------------------------------------------------------------
-- Integrity triggers (defence in depth)
-- ---------------------------------------------------------------------------
-- The RPCs below are the only write path in the application, but this trigger
-- keeps the "exactly two members" invariant true no matter how a row is
-- inserted. Diong Pass 4 ships direct messages only — no group chat.

create function public.enforce_conversation_member_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (
    select count(*) from public.conversation_members
    where conversation_id = new.conversation_id
  ) >= 2 then
    raise exception using errcode = '23514',
      message = 'A direct conversation supports exactly two members.';
  end if;
  return new;
end;
$$;

create trigger conversation_members_enforce_limit
before insert on public.conversation_members
for each row execute function public.enforce_conversation_member_limit();

-- ---------------------------------------------------------------------------
-- Internal helper function
-- ---------------------------------------------------------------------------
-- security definer so it can be used inside the RLS policies below without
-- recursion: it reads public.conversation_members as the function owner
-- (bypassing that table's own RLS), exactly the way public.blocked_between()
-- (Pass 2) reads public.blocks as the function owner.

create function public.is_conversation_member(p_conversation_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.conversation_members
    where conversation_id = p_conversation_id and user_id = p_user_id
  );
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

revoke all on public.conversations from anon, authenticated;
revoke all on public.conversation_members from anon, authenticated;
revoke all on public.messages from anon, authenticated;

-- Reads only. Every write goes through a SECURITY DEFINER RPC below, matching
-- the Pass 1 / Pass 2 / Pass 3 RPC-only model.
grant select on public.conversations to authenticated;
grant select on public.conversation_members to authenticated;
grant select on public.messages to authenticated;

create policy "Members can read their conversations"
on public.conversations for select
to authenticated
using (public.is_conversation_member(id, (select auth.uid())));

create policy "Members can read conversation membership"
on public.conversation_members for select
to authenticated
using (public.is_conversation_member(conversation_id, (select auth.uid())));

create policy "Members can read their messages"
on public.messages for select
to authenticated
using (public.is_conversation_member(conversation_id, (select auth.uid())));

-- ---------------------------------------------------------------------------
-- Mutations — the only write path for conversations and messages
-- ---------------------------------------------------------------------------

-- get_or_create_conversation: returns the single direct conversation between
-- the caller and p_other_user_id, creating it if it does not yet exist.
-- Blocked in either direction, a missing/incomplete target, a null target or
-- the caller's own id are all rejected — the same guard shape as
-- follow_user(). Safe under concurrent calls: the unique(user_min_id,
-- user_max_id) constraint is the final authority, not this function's
-- select-then-insert.
create function public.get_or_create_conversation(p_other_user_id uuid)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_min uuid;
  v_max uuid;
  v_conversation_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if p_other_user_id is null or p_other_user_id = v_viewer then
    raise exception using errcode = '22023', message = 'You cannot message this account.';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = p_other_user_id and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  if public.blocked_between(v_viewer, p_other_user_id) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  v_min := least(v_viewer, p_other_user_id);
  v_max := greatest(v_viewer, p_other_user_id);

  insert into public.conversations (user_min_id, user_max_id)
  values (v_min, v_max)
  on conflict (user_min_id, user_max_id) do nothing;

  select id into v_conversation_id
  from public.conversations
  where user_min_id = v_min and user_max_id = v_max;

  insert into public.conversation_members (conversation_id, user_id)
  values (v_conversation_id, v_viewer), (v_conversation_id, p_other_user_id)
  on conflict (conversation_id, user_id) do nothing;

  return v_conversation_id;
end;
$$;

-- send_message: the only way a row is ever inserted into public.messages.
-- sender_id is always auth.uid() — never a client-supplied column. Requires
-- live membership and no block between the two participants; stamps the
-- conversation's last_message_at and the sender's own last_read_at (so a
-- sender never sees their own message as unread).
create function public.send_message(p_conversation_id bigint, p_body text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
  v_other uuid;
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 5000 then
    raise exception using errcode = '22023', message = 'Write between 1 and 5000 characters.';
  end if;

  if not public.is_conversation_member(p_conversation_id, v_viewer) then
    raise exception using errcode = '42501', message = 'This conversation is not available.';
  end if;

  select cm.user_id into v_other
  from public.conversation_members cm
  where cm.conversation_id = p_conversation_id and cm.user_id <> v_viewer;

  if v_other is not null and public.blocked_between(v_viewer, v_other) then
    raise exception using errcode = '42501', message = 'This conversation is not available.';
  end if;

  insert into public.messages (conversation_id, sender_id, body)
  values (p_conversation_id, v_viewer, v_body)
  returning id into v_new_id;

  update public.conversations
  set last_message_at = now()
  where id = p_conversation_id;

  update public.conversation_members
  set last_read_at = now()
  where conversation_id = p_conversation_id and user_id = v_viewer;

  return v_new_id;
end;
$$;

-- mark_conversation_read: the only way conversation_members.last_read_at
-- changes for a reader. Silently does nothing if the caller is not a member
-- (no row to update) rather than raising, since a page can call this
-- speculatively right after resolving the conversation.
create function public.mark_conversation_read(p_conversation_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  update public.conversation_members
  set last_read_at = now()
  where conversation_id = p_conversation_id and user_id = v_viewer;
end;
$$;

-- ---------------------------------------------------------------------------
-- Read RPCs — inbox, conversation, messages, unread count
-- ---------------------------------------------------------------------------

-- The viewer's inbox: one row per conversation that has at least one message,
-- most recently active first, block filtered (a conversation with either
-- account now blocking the other is hidden entirely, matching the Pass 3
-- notifications block policy). Keyset paginated on (last_message_at, id).
create function public.list_conversations(
  p_before_last_message_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  other_user_id uuid,
  other_username text,
  other_display_name text,
  last_message_body text,
  last_message_at timestamptz,
  unread boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    c.id,
    pr.id,
    pr.username,
    pr.display_name,
    lm.body,
    c.last_message_at,
    (
      lm.created_at is not null
      and lm.sender_id <> v_viewer
      and lm.created_at > coalesce(cm.last_read_at, '-infinity'::timestamptz)
    )
  from public.conversation_members cm
  join public.conversations c on c.id = cm.conversation_id
  join public.conversation_members other_cm
    on other_cm.conversation_id = c.id and other_cm.user_id <> v_viewer
  join public.profiles pr on pr.id = other_cm.user_id
  left join lateral (
    select m.body, m.created_at, m.sender_id
    from public.messages m
    where m.conversation_id = c.id
    order by m.created_at desc, m.id desc
    limit 1
  ) lm on true
  where cm.user_id = v_viewer
    and c.last_message_at is not null
    and not public.blocked_between(v_viewer, other_cm.user_id)
    and (
      p_before_last_message_at is null
      or (c.last_message_at, c.id)
         < (p_before_last_message_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by c.last_message_at desc, c.id desc
  limit v_limit;
end;
$$;

-- One conversation from the viewer's point of view, or no row when the
-- caller is not a member, the id does not exist, or a block now stands
-- between the two participants. The caller treats "no row" as notFound().
create function public.get_conversation(p_conversation_id bigint)
returns table (
  id bigint,
  other_user_id uuid,
  other_username text,
  other_display_name text,
  created_at timestamptz
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.is_conversation_member(p_conversation_id, v_viewer) then
    return;
  end if;

  return query
  select
    c.id,
    pr.id,
    pr.username,
    pr.display_name,
    c.created_at
  from public.conversations c
  join public.conversation_members cm
    on cm.conversation_id = c.id and cm.user_id <> v_viewer
  join public.profiles pr on pr.id = cm.user_id
  where c.id = p_conversation_id
    and not public.blocked_between(v_viewer, cm.user_id);
end;
$$;

-- Messages in one conversation, newest first, keyset paginated on
-- (created_at, id) — the same cursor shape as list_feed(). Returns nothing
-- when the caller is not a member or a block now stands between the two
-- participants, rather than raising, so a page can render an empty state.
create function public.list_messages(
  p_conversation_id bigint,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  sender_id uuid,
  body text,
  created_at timestamptz,
  is_own boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
  v_other uuid;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.is_conversation_member(p_conversation_id, v_viewer) then
    return;
  end if;

  select cm.user_id into v_other
  from public.conversation_members cm
  where cm.conversation_id = p_conversation_id and cm.user_id <> v_viewer;

  if v_other is not null and public.blocked_between(v_viewer, v_other) then
    return;
  end if;

  return query
  select
    m.id,
    m.sender_id,
    m.body,
    m.created_at,
    m.sender_id = v_viewer
  from public.messages m
  where m.conversation_id = p_conversation_id
    and (
      p_before_created_at is null
      or (m.created_at, m.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by m.created_at desc, m.id desc
  limit v_limit;
end;
$$;

-- Total unread message count across every non-blocked conversation the
-- viewer is a member of. Powers the Messages nav badge.
create function public.get_unread_message_count()
returns integer
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_count integer;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select count(*)::integer into v_count
  from public.messages m
  join public.conversation_members cm
    on cm.conversation_id = m.conversation_id and cm.user_id = v_viewer
  join public.conversation_members other_cm
    on other_cm.conversation_id = m.conversation_id and other_cm.user_id <> v_viewer
  where m.sender_id <> v_viewer
    and m.created_at > coalesce(cm.last_read_at, '-infinity'::timestamptz)
    and not public.blocked_between(v_viewer, other_cm.user_id);

  return coalesce(v_count, 0);
end;
$$;

-- ---------------------------------------------------------------------------
-- Notifications extension — new_message
-- ---------------------------------------------------------------------------
-- public.notifications already exists (Pass 3, 202609100004). This is
-- additive schema evolution against that table via ALTER TABLE / CREATE OR
-- REPLACE FUNCTION in this new migration file — the already-applied
-- 202609100004 migration file itself is not touched, exactly the precedent
-- set by 202609120001_fix_social_profile_username.sql. The existing
-- notification types, their triggers (notify_new_follower / notify_post_like
-- / notify_post_comment) and list_notifications()'s signature are unchanged.

alter table public.notifications drop constraint notifications_type_allowed;
alter table public.notifications add constraint notifications_type_allowed check (notification_type in (
  'new_follower',
  'post_like',
  'post_comment',
  'comment_reply',
  'new_message'
));

alter table public.notifications drop constraint notifications_entity_type_allowed;
alter table public.notifications add constraint notifications_entity_type_allowed check (
  entity_type is null or entity_type in ('profile', 'post', 'comment', 'conversation')
);

alter table public.notifications drop constraint notifications_type_entity_consistent;
alter table public.notifications add constraint notifications_type_entity_consistent check (
  (notification_type = 'new_follower'
    and entity_type = 'profile' and entity_id is null)
  or (notification_type = 'post_like'
    and entity_type = 'post' and entity_id is not null)
  or (notification_type = 'post_comment'
    and entity_type = 'post' and entity_id is not null)
  or (notification_type = 'comment_reply'
    and entity_type = 'comment' and entity_id is not null)
  or (notification_type = 'new_message'
    and entity_type = 'conversation' and entity_id is not null)
);

-- Dedup policy: unlike a like/follow (idempotent toggle) or a comment (each a
-- distinct real event, never deduplicated), a message thread can produce many
-- events in quick succession. To avoid one notification per chat message, the
-- recipient gets at most one UNREAD 'new_message' notification per
-- conversation at a time — a further message from the same conversation
-- while that notification is still unread does not create a second one; once
-- the recipient reads it (mark_notification_read / mark_all_notifications_read),
-- the next new message creates a fresh one. This is deterministic and needs
-- no time-window heuristic, the same shape of reasoning Pass 3 documented for
-- follow / like dedup.
create function public.notify_new_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_recipient uuid;
begin
  select cm.user_id into v_recipient
  from public.conversation_members cm
  where cm.conversation_id = new.conversation_id
    and cm.user_id <> new.sender_id
  limit 1;

  if v_recipient is null then
    return new;
  end if;

  if not exists (
    select 1 from public.notifications
    where user_id = v_recipient
      and actor_user_id = new.sender_id
      and notification_type = 'new_message'
      and entity_id = new.conversation_id
      and read_at is null
  ) then
    insert into public.notifications
      (user_id, actor_user_id, notification_type, entity_type, entity_id)
    values
      (v_recipient, new.sender_id, 'new_message', 'conversation', new.conversation_id);
  end if;

  return new;
end;
$$;

create trigger messages_notify_new_message
after insert on public.messages
for each row execute function public.notify_new_message();

-- list_notifications() (Pass 3) resolves a per-row "is the target still
-- navigable" flag. Re-created here (same signature, same nine columns) only
-- to add the 'new_message' branch to that resolution — membership + no block,
-- via is_conversation_member(), which did not exist when Pass 3 was written.
-- Every other branch is copied unchanged from 202609100004_notifications_
-- discover_search.sql.
create or replace function public.list_notifications(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  notification_type text,
  entity_type text,
  entity_id bigint,
  actor_user_id uuid,
  actor_username text,
  actor_display_name text,
  target_post_id bigint,
  target_available boolean,
  read_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    n.id,
    n.notification_type,
    n.entity_type,
    n.entity_id,
    n.actor_user_id,
    pr.username,
    pr.display_name,
    case
      when n.notification_type in ('post_like', 'post_comment')
        then case when public.viewer_can_see_post(n.entity_id) then n.entity_id else null end
      when n.notification_type = 'comment_reply'
        then case
          when c.deleted_at is null and public.viewer_can_see_post(c.post_id)
            then c.post_id
          else null
        end
      else null
    end,
    case
      when n.notification_type = 'new_follower' then
        exists (
          select 1 from public.profiles p
          where p.id = n.actor_user_id and p.onboarding_completed
        )
      when n.notification_type in ('post_like', 'post_comment') then
        public.viewer_can_see_post(n.entity_id)
      when n.notification_type = 'comment_reply' then
        c.deleted_at is null and public.viewer_can_see_post(c.post_id)
      when n.notification_type = 'new_message' then
        public.is_conversation_member(n.entity_id, v_viewer)
      else false
    end,
    n.read_at,
    n.created_at
  from public.notifications n
  left join public.profiles pr on pr.id = n.actor_user_id
  left join public.post_comments c
    on n.notification_type = 'comment_reply' and c.id = n.entity_id
  where n.user_id = v_viewer
    and (
      n.actor_user_id is null
      or not public.blocked_between(v_viewer, n.actor_user_id)
    )
    and (
      p_before_created_at is null
      or (n.created_at, n.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by n.created_at desc, n.id desc
  limit v_limit;
end;
$$;

-- Execution privileges are not reset by CREATE OR REPLACE FUNCTION when the
-- signature is unchanged (they already are: authenticated only, no anon /
-- public, from 202609100004). Reasserted here anyway, defensively and
-- idempotently, purely for migration self-documentation — this changes
-- nothing.
revoke all on function public.list_notifications(timestamptz, bigint, integer) from public, anon;
grant execute on function public.list_notifications(timestamptz, bigint, integer) to authenticated;

-- Trigger functions are invoked only by their triggers, never called directly.
revoke all on function public.notify_new_message() from public, anon, authenticated;
revoke all on function public.enforce_conversation_member_limit() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Execution privileges
-- ---------------------------------------------------------------------------

revoke all on function public.is_conversation_member(bigint, uuid) from public, anon;
revoke all on function public.get_or_create_conversation(uuid) from public, anon;
revoke all on function public.send_message(bigint, text) from public, anon;
revoke all on function public.mark_conversation_read(bigint) from public, anon;
revoke all on function public.list_conversations(timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_conversation(bigint) from public, anon;
revoke all on function public.list_messages(bigint, timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_unread_message_count() from public, anon;

grant execute on function public.is_conversation_member(bigint, uuid) to authenticated;
grant execute on function public.get_or_create_conversation(uuid) to authenticated;
grant execute on function public.send_message(bigint, text) to authenticated;
grant execute on function public.mark_conversation_read(bigint) to authenticated;
grant execute on function public.list_conversations(timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_conversation(bigint) to authenticated;
grant execute on function public.list_messages(bigint, timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_unread_message_count() to authenticated;

commit;
