begin;

-- Diong Social Content — Social Network Pass 2: posts, feed, comments, likes,
-- bookmarks.
--
-- Additive only. Adds four tables (public.posts, public.post_comments,
-- public.post_likes, public.post_bookmarks), their RLS, two integrity triggers,
-- two internal helper functions and the SECURITY DEFINER RPCs that are the only
-- read path for the feed / detail / lists and the only write path for every
-- post, comment, like and bookmark mutation. Nothing in this file alters an
-- existing table, function, grant, policy or trigger. Daily Prime, Prime
-- history / reflections, Connections and the Pass 1 follow / block graph are
-- untouched.
--
-- Apply once, in order, after 202609100002_social_graph.sql. Depends on
-- public.profiles / auth.users (202607190001), public.follows / public.blocks
-- (202609100002) and public.set_updated_at() (202607190001). Each migration is a
-- single transaction and is NOT idempotent — never re-run a migration that
-- already succeeded.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_type text not null,
  body text not null,
  visibility text not null default 'public',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  constraint posts_body_not_empty check (char_length(btrim(body)) between 1 and 5000),
  constraint posts_type_allowed check (post_type in (
    'update',
    'reflection',
    'progress',
    'learning',
    'achievement',
    'question',
    'resource'
  )),
  constraint posts_visibility_allowed check (visibility in (
    'public',
    'followers',
    'private'
  ))
);

create table public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Referential integrity + the "same post" rule are both enforced by the
  -- composite foreign key post_comments_parent_same_post below.
  parent_comment_id bigint,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  constraint post_comments_body_not_empty
    check (char_length(btrim(body)) between 1 and 2000),
  -- One reply level only: a comment is either a root (parent null) or a direct
  -- reply to a root. The enforce_comment_one_level trigger below rejects a
  -- reply whose parent is itself a reply, or whose parent is on another post.
  constraint post_comments_id_post_id_key unique (id, post_id),
  constraint post_comments_parent_same_post
    foreign key (parent_comment_id, post_id)
    references public.post_comments (id, post_id) on delete cascade
);

create table public.post_likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  -- One like per user per post. The database is the final authority on
  -- idempotency; the RPCs insert on conflict do nothing.
  primary key (user_id, post_id)
);

create table public.post_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

-- Feed / profile / list access paths.
create index posts_user_created_idx
  on public.posts (user_id, created_at desc)
  where deleted_at is null;
create index posts_created_idx
  on public.posts (created_at desc, id desc)
  where deleted_at is null;
create index posts_visibility_created_idx
  on public.posts (visibility, created_at desc)
  where deleted_at is null;

create index post_comments_post_created_idx
  on public.post_comments (post_id, created_at);
create index post_comments_parent_idx
  on public.post_comments (parent_comment_id)
  where parent_comment_id is not null;
create index post_comments_user_idx on public.post_comments (user_id);

-- The (user_id, post_id) primary keys serve "did this user like / bookmark X".
-- Add the reverse for "how many likes does X have" and the saved-list order.
create index post_likes_post_id_idx on public.post_likes (post_id);
create index post_bookmarks_user_created_idx
  on public.post_bookmarks (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Integrity triggers (defence in depth)
-- ---------------------------------------------------------------------------
-- The RPCs below are the only write path in the application, but these triggers
-- keep the comment-depth invariant true no matter how a row is inserted.

create function public.enforce_comment_one_level()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.parent_comment_id is not null then
    if not exists (
      select 1
      from public.post_comments parent
      where parent.id = new.parent_comment_id
        and parent.post_id = new.post_id
        and parent.parent_comment_id is null
    ) then
      raise exception using errcode = '22023',
        message = 'A reply must point at a top-level comment on the same post.';
    end if;
  end if;
  return new;
end;
$$;

create trigger post_comments_enforce_one_level
before insert on public.post_comments
for each row execute function public.enforce_comment_one_level();

create trigger post_comments_set_updated_at
before update on public.post_comments
for each row execute function public.set_updated_at();

create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Internal helper functions
-- ---------------------------------------------------------------------------
-- Both are SECURITY DEFINER because they read public.blocks, which a client can
-- only read where it is the blocker. They are used by the RLS policies and the
-- RPCs; EXECUTE is granted to authenticated (each returns only a boolean about
-- the calling user's own relationship to one other account / post).

-- Is there a block in either direction between the two users?
create function public.blocked_between(p_a uuid, p_b uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1 from public.blocks
    where (blocker_id = p_a and blocked_id = p_b)
       or (blocker_id = p_b and blocked_id = p_a)
  );
$$;

-- Can the current user (auth.uid()) see this post? Encapsulates the full
-- visibility model: a live (non-deleted) post is visible to its author always;
-- to everyone else only when no block stands between them and the author AND
-- the post is public, or followers-only and they follow the author. Private
-- posts are visible to the author alone.
create function public.viewer_can_see_post(p_post_id bigint)
returns boolean
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_post public.posts;
begin
  if v_viewer is null then
    return false;
  end if;

  select * into v_post from public.posts where id = p_post_id;
  if not found or v_post.deleted_at is not null then
    return false;
  end if;

  if v_post.user_id = v_viewer then
    return true;
  end if;

  if public.blocked_between(v_viewer, v_post.user_id) then
    return false;
  end if;

  if v_post.visibility = 'public' then
    return true;
  end if;

  if v_post.visibility = 'followers' then
    return exists (
      select 1 from public.follows
      where follower_id = v_viewer and following_id = v_post.user_id
    );
  end if;

  return false;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.posts enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_bookmarks enable row level security;

revoke all on public.posts from anon, authenticated;
revoke all on public.post_comments from anon, authenticated;
revoke all on public.post_likes from anon, authenticated;
revoke all on public.post_bookmarks from anon, authenticated;

-- Reads only. Every write goes through a SECURITY DEFINER RPC below, matching
-- the Pass 1 follows / blocks RPC-only model.
grant select on public.posts to authenticated;
grant select on public.post_comments to authenticated;
grant select on public.post_likes to authenticated;
grant select on public.post_bookmarks to authenticated;

-- posts: a live post is readable by its author, or by anyone with no block
-- between them and the author when it is public or followers-only-and-followed.
-- Soft-deleted posts are readable by nobody. The feed / detail / list RPCs run
-- as SECURITY DEFINER and re-apply exactly this rule; this policy is the
-- defence-in-depth floor for any direct select.
create policy "Read visible posts"
on public.posts for select
to authenticated
using (
  deleted_at is null
  and (
    user_id = (select auth.uid())
    or (
      not public.blocked_between((select auth.uid()), user_id)
      and (
        visibility = 'public'
        or (
          visibility = 'followers'
          and exists (
            select 1 from public.follows
            where follower_id = (select auth.uid())
              and following_id = posts.user_id
          )
        )
      )
    )
  )
);

-- post_comments: readable when the parent post is visible to the viewer and no
-- block stands between the viewer and the comment author. Deleted comments stay
-- selectable so a thread keeps its shape; the list RPC blanks their body.
create policy "Read comments on visible posts"
on public.post_comments for select
to authenticated
using (
  public.viewer_can_see_post(post_id)
  and not public.blocked_between((select auth.uid()), user_id)
);

-- post_likes / post_bookmarks: a user reads only their own rows. Like counts
-- and "who liked" are never exposed row-by-row; counts come from the RPCs.
-- Bookmarks are private by design.
create policy "Read own likes"
on public.post_likes for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Read own bookmarks"
on public.post_bookmarks for select
to authenticated
using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- Read RPCs — feed, detail, user posts, bookmarks, comments, engagement
-- ---------------------------------------------------------------------------
-- All: language plpgsql / sql, security definer, stable, search_path = '',
-- every object schema-qualified, viewer from auth.uid(), keyset pagination with
-- a hard page cap, engagement counts folded in so callers never issue an
-- N+1 per-post query.

-- Chronological feed: the viewer's own posts, plus public posts and
-- followers-only posts by accounts they follow, newest first, block-filtered.
-- Keyset paginated on (created_at, id).
create function public.list_feed(
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer
  from public.posts p
  join public.profiles pr on pr.id = p.user_id and pr.onboarding_completed
  where p.deleted_at is null
    and not public.blocked_between(v_viewer, p.user_id)
    and (
      p.user_id = v_viewer
      or p.visibility = 'public'
      or (
        p.visibility = 'followers'
        and exists (
          select 1 from public.follows f
          where f.follower_id = v_viewer and f.following_id = p.user_id
        )
      )
    )
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- One post from the viewer's point of view, or no row when it is not visible
-- (missing, deleted, private, followers-only-and-not-followed, or blocked).
create function public.get_post(p_post_id bigint)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    return;
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer
  from public.posts p
  join public.profiles pr on pr.id = p.user_id
  where p.id = p_post_id;
end;
$$;

-- Posts by one author that the viewer is allowed to see, newest first, keyset
-- paginated. Returns nothing when a block stands between the two accounts.
create function public.list_user_posts(
  p_author_id uuid,
  p_before_created_at timestamptz default null,
  p_before_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if p_author_id is null or public.blocked_between(v_viewer, p_author_id) then
    return;
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    ),
    p.user_id = v_viewer
  from public.posts p
  join public.profiles pr on pr.id = p.user_id
  where p.user_id = p_author_id
    and p.deleted_at is null
    and (
      p.user_id = v_viewer
      or p.visibility = 'public'
      or (
        p.visibility = 'followers'
        and exists (
          select 1 from public.follows f
          where f.follower_id = v_viewer and f.following_id = p.user_id
        )
      )
    )
    and (
      p_before_created_at is null
      or (p.created_at, p.id)
         < (p_before_created_at, coalesce(p_before_id, 9223372036854775807))
    )
  order by p.created_at desc, p.id desc
  limit v_limit;
end;
$$;

-- The viewer's bookmarked posts, most recently saved first, keyset paginated on
-- the bookmark timestamp. A post that is no longer visible (deleted, blocked,
-- visibility narrowed) is dropped from the result — never exposed.
create function public.list_bookmarks(
  p_before_created_at timestamptz default null,
  p_before_post_id bigint default null,
  p_limit integer default 20
)
returns table (
  id bigint,
  user_id uuid,
  post_type text,
  body text,
  visibility text,
  created_at timestamptz,
  edited_at timestamptz,
  author_username text,
  author_display_name text,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean,
  is_author boolean,
  bookmarked_at timestamptz
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 20);
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    p.user_id,
    p.post_type,
    p.body,
    p.visibility,
    p.created_at,
    p.edited_at,
    pr.username,
    pr.display_name,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb2
      where pb2.post_id = p.id and pb2.user_id = v_viewer
    ),
    p.user_id = v_viewer,
    pb.created_at
  from public.post_bookmarks pb
  join public.posts p on p.id = pb.post_id
  join public.profiles pr on pr.id = p.user_id
  where pb.user_id = v_viewer
    and public.viewer_can_see_post(p.id)
    and (
      p_before_created_at is null
      or (pb.created_at, pb.post_id)
         < (p_before_created_at, coalesce(p_before_post_id, 9223372036854775807))
    )
  order by pb.created_at desc, pb.post_id desc
  limit v_limit;
end;
$$;

-- Engagement counts for a set of posts, block/visibility filtered. Handy where
-- a caller already has post ids and only needs fresh counts.
create function public.get_post_engagement(p_post_ids bigint[])
returns table (
  post_id bigint,
  like_count integer,
  comment_count integer,
  viewer_liked boolean,
  viewer_bookmarked boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  return query
  select
    p.id,
    (select count(*)::integer from public.post_likes pl where pl.post_id = p.id),
    (select count(*)::integer from public.post_comments pc
      where pc.post_id = p.id and pc.deleted_at is null),
    exists (
      select 1 from public.post_likes pl
      where pl.post_id = p.id and pl.user_id = v_viewer
    ),
    exists (
      select 1 from public.post_bookmarks pb
      where pb.post_id = p.id and pb.user_id = v_viewer
    )
  from public.posts p
  where p.id = any(p_post_ids)
    and public.viewer_can_see_post(p.id);
end;
$$;

-- Comments for one visible post: top-level comments and their single reply
-- level, oldest first, block-filtered. A deleted top-level comment is returned
-- as a tombstone (body null, is_deleted true) only when it still has a live
-- reply, so a reply keeps its context; deleted replies are dropped. Capped at
-- 500 rows for Pass 2.
create function public.list_post_comments(p_post_id bigint)
returns table (
  id bigint,
  parent_comment_id bigint,
  user_id uuid,
  author_username text,
  author_display_name text,
  body text,
  created_at timestamptz,
  edited_at timestamptz,
  is_deleted boolean,
  is_author boolean
)
language plpgsql
security definer
stable
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    return;
  end if;

  return query
  select
    c.id,
    c.parent_comment_id,
    c.user_id,
    pr.username,
    pr.display_name,
    case when c.deleted_at is null then c.body else null end,
    c.created_at,
    c.edited_at,
    c.deleted_at is not null,
    c.user_id = v_viewer
  from public.post_comments c
  join public.profiles pr on pr.id = c.user_id
  where c.post_id = p_post_id
    and not public.blocked_between(v_viewer, c.user_id)
    and (
      c.deleted_at is null
      or (
        c.parent_comment_id is null
        and exists (
          select 1 from public.post_comments r
          where r.parent_comment_id = c.id and r.deleted_at is null
        )
      )
    )
  order by
    coalesce(c.parent_comment_id, c.id),
    (c.parent_comment_id is not null),
    c.created_at,
    c.id
  limit 500;
end;
$$;

-- ---------------------------------------------------------------------------
-- Mutation RPCs — the only write path for posts, comments, likes, bookmarks
-- ---------------------------------------------------------------------------

create function public.create_post(
  p_post_type text,
  p_body text,
  p_visibility text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.profiles where id = v_viewer and onboarding_completed
  ) then
    raise exception using errcode = '42501', message = 'This account is not available.';
  end if;

  if p_post_type is null or p_post_type not in (
    'update', 'reflection', 'progress', 'learning', 'achievement', 'question', 'resource'
  ) then
    raise exception using errcode = '22023', message = 'Choose a valid post type.';
  end if;

  if p_visibility is null or p_visibility not in ('public', 'followers', 'private') then
    raise exception using errcode = '22023', message = 'Choose a valid visibility.';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 5000 then
    raise exception using errcode = '22023', message = 'Write between 1 and 5000 characters.';
  end if;

  insert into public.posts (user_id, post_type, body, visibility)
  values (v_viewer, p_post_type, v_body, p_visibility)
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- Edit the body and/or visibility of the caller's own live post. id, user_id,
-- post_type and created_at can never change here. edited_at is stamped.
create function public.update_post(
  p_post_id bigint,
  p_body text,
  p_visibility text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if p_visibility is null or p_visibility not in ('public', 'followers', 'private') then
    raise exception using errcode = '22023', message = 'Choose a valid visibility.';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 5000 then
    raise exception using errcode = '22023', message = 'Write between 1 and 5000 characters.';
  end if;

  update public.posts
  set body = v_body,
      visibility = p_visibility,
      edited_at = now()
  where id = p_post_id
    and user_id = v_viewer
    and deleted_at is null;

  if not found then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;
end;
$$;

-- Soft delete: mark the caller's own post deleted. The row and its comments
-- stay for social integrity but become invisible everywhere.
create function public.soft_delete_post(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  update public.posts
  set deleted_at = now()
  where id = p_post_id
    and user_id = v_viewer
    and deleted_at is null;

  if not found then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;
end;
$$;

-- Add a comment, or a reply to a top-level comment, on a post the caller can
-- see. A reply's parent must be a root comment on the same post (also enforced
-- by the enforce_comment_one_level trigger).
create function public.create_comment(
  p_post_id bigint,
  p_body text,
  p_parent_comment_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
  v_author uuid;
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 2000 then
    raise exception using errcode = '22023', message = 'Write between 1 and 2000 characters.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  select user_id into v_author from public.posts where id = p_post_id;
  if public.blocked_between(v_viewer, v_author) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  if p_parent_comment_id is not null then
    if not exists (
      select 1 from public.post_comments parent
      where parent.id = p_parent_comment_id
        and parent.post_id = p_post_id
        and parent.parent_comment_id is null
        and parent.deleted_at is null
    ) then
      raise exception using errcode = '22023', message = 'That comment can no longer be replied to.';
    end if;
  end if;

  insert into public.post_comments (post_id, user_id, parent_comment_id, body)
  values (p_post_id, v_viewer, p_parent_comment_id, v_body)
  returning id into v_new_id;

  return v_new_id;
end;
$$;

create function public.edit_own_comment(p_comment_id bigint, p_body text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_body text := btrim(coalesce(p_body, ''));
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 2000 then
    raise exception using errcode = '22023', message = 'Write between 1 and 2000 characters.';
  end if;

  update public.post_comments
  set body = v_body,
      edited_at = now()
  where id = p_comment_id
    and user_id = v_viewer
    and deleted_at is null;

  if not found then
    raise exception using errcode = '42501', message = 'This comment is not available.';
  end if;
end;
$$;

create function public.delete_own_comment(p_comment_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  update public.post_comments
  set deleted_at = now()
  where id = p_comment_id
    and user_id = v_viewer
    and deleted_at is null;

  if not found then
    raise exception using errcode = '42501', message = 'This comment is not available.';
  end if;
end;
$$;

-- like_post / bookmark_post: idempotent (insert on conflict do nothing). The
-- post must be visible and unblocked. unlike_post / remove_bookmark are plain
-- idempotent deletes.
create function public.like_post(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_author uuid;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  select user_id into v_author from public.posts where id = p_post_id;
  if public.blocked_between(v_viewer, v_author) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  insert into public.post_likes (user_id, post_id)
  values (v_viewer, p_post_id)
  on conflict (user_id, post_id) do nothing;
end;
$$;

create function public.unlike_post(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  delete from public.post_likes
  where user_id = v_viewer and post_id = p_post_id;
end;
$$;

create function public.bookmark_post(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_author uuid;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not public.viewer_can_see_post(p_post_id) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  select user_id into v_author from public.posts where id = p_post_id;
  if public.blocked_between(v_viewer, v_author) then
    raise exception using errcode = '42501', message = 'This post is not available.';
  end if;

  insert into public.post_bookmarks (user_id, post_id)
  values (v_viewer, p_post_id)
  on conflict (user_id, post_id) do nothing;
end;
$$;

create function public.remove_bookmark(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  delete from public.post_bookmarks
  where user_id = v_viewer and post_id = p_post_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Execution privileges
-- ---------------------------------------------------------------------------

revoke all on function public.blocked_between(uuid, uuid) from public, anon;
revoke all on function public.viewer_can_see_post(bigint) from public, anon;
revoke all on function public.list_feed(timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_post(bigint) from public, anon;
revoke all on function public.list_user_posts(uuid, timestamptz, bigint, integer) from public, anon;
revoke all on function public.list_bookmarks(timestamptz, bigint, integer) from public, anon;
revoke all on function public.get_post_engagement(bigint[]) from public, anon;
revoke all on function public.list_post_comments(bigint) from public, anon;
revoke all on function public.create_post(text, text, text) from public, anon;
revoke all on function public.update_post(bigint, text, text) from public, anon;
revoke all on function public.soft_delete_post(bigint) from public, anon;
revoke all on function public.create_comment(bigint, text, bigint) from public, anon;
revoke all on function public.edit_own_comment(bigint, text) from public, anon;
revoke all on function public.delete_own_comment(bigint) from public, anon;
revoke all on function public.like_post(bigint) from public, anon;
revoke all on function public.unlike_post(bigint) from public, anon;
revoke all on function public.bookmark_post(bigint) from public, anon;
revoke all on function public.remove_bookmark(bigint) from public, anon;

grant execute on function public.blocked_between(uuid, uuid) to authenticated;
grant execute on function public.viewer_can_see_post(bigint) to authenticated;
grant execute on function public.list_feed(timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_post(bigint) to authenticated;
grant execute on function public.list_user_posts(uuid, timestamptz, bigint, integer) to authenticated;
grant execute on function public.list_bookmarks(timestamptz, bigint, integer) to authenticated;
grant execute on function public.get_post_engagement(bigint[]) to authenticated;
grant execute on function public.list_post_comments(bigint) to authenticated;
grant execute on function public.create_post(text, text, text) to authenticated;
grant execute on function public.update_post(bigint, text, text) to authenticated;
grant execute on function public.soft_delete_post(bigint) to authenticated;
grant execute on function public.create_comment(bigint, text, bigint) to authenticated;
grant execute on function public.edit_own_comment(bigint, text) to authenticated;
grant execute on function public.delete_own_comment(bigint) to authenticated;
grant execute on function public.like_post(bigint) to authenticated;
grant execute on function public.unlike_post(bigint) to authenticated;
grant execute on function public.bookmark_post(bigint) to authenticated;
grant execute on function public.remove_bookmark(bigint) to authenticated;

-- Trigger function is invoked only by its trigger, never called directly.
revoke all on function public.enforce_comment_one_level() from public, anon, authenticated;

commit;
