begin;

-- Diong Personal Development — Pass 6: Goals, Habits and a Private Journal.
--
-- Additive only. Adds five tables (public.goals, public.goal_milestones,
-- public.habits, public.habit_checkins, public.journal_entries), their
-- indexes, RLS, five triggers and four SECURITY DEFINER RPCs. Nothing in
-- this file alters an existing table, function, grant, policy or trigger.
-- Daily Prime, Connections, the social graph, posts/feed, notifications,
-- Discover/Search, direct messages and communities are untouched.
--
-- Apply once, in order, after 202609120003_communities.sql. Depends on
-- public.profiles / auth.users (202607190001) and public.prime_assignments
-- (202607270001) for the journal's optional Daily Prime link. Each migration
-- is a single transaction and is NOT idempotent — never re-run a migration
-- that already succeeded.
--
-- Privacy: every table here is strictly owner-only. There is no shared,
-- public or cross-user select policy anywhere in this file. None of this
-- data is ever surfaced by the feed, Discover, Search, public profiles,
-- communities, messages, or notifications sent to other users.
--
-- Architecture decision (mirrors the Connections Phase A/B split): goals,
-- habits and journal_entries are plain owner-CRUD tables with column-scoped,
-- revoke-first grants — the same model public.connections already uses.
-- goal_milestones and habit_checkins are the "child" tables (one goal has
-- many milestones; one habit has many check-ins) and follow the
-- connection_interactions precedent instead: SELECT only for the owner, and
-- RPC-only writes, so ownership, position/streak-affecting inserts and
-- append/toggle semantics stay database-authoritative. Two small BEFORE
-- UPDATE triggers (mirroring the existing public.set_updated_at() pattern)
-- keep completed_at / archived_at system-managed and excluded from every
-- grant, so a client can never forge them.

-- ---------------------------------------------------------------------------
-- goals
-- ---------------------------------------------------------------------------

create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null default '',
  category text,
  status text not null default 'active',
  target_date date,
  progress_percent integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint goals_title_length check (char_length(btrim(title)) between 1 and 120),
  constraint goals_description_length check (char_length(description) <= 3000),
  constraint goals_category_length
    check (category is null or char_length(btrim(category)) between 1 and 60),
  constraint goals_status_allowed
    check (status in ('active', 'paused', 'completed', 'archived')),
  constraint goals_progress_percent_range
    check (progress_percent between 0 and 100),
  -- A completed goal is always shown at 100%; setGoalProgress cannot leave a
  -- completed goal at a partial value, and reopening (status leaves
  -- 'completed') is required before progress can change again. The
  -- apply_goal_completion_status() trigger below is what keeps a legitimate
  -- status change consistent with this check in the same statement.
  constraint goals_completed_progress_full
    check (status <> 'completed' or progress_percent = 100),
  -- Target for the composite foreign key from goal_milestones, the same
  -- pattern connections_id_user_id_key uses for connection_interactions.
  constraint goals_id_user_id_key unique (id, user_id)
);

create table public.goal_milestones (
  id bigint generated by default as identity primary key,
  goal_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  position integer not null,
  is_completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint goal_milestones_title_length
    check (char_length(btrim(title)) between 1 and 200),
  constraint goal_milestones_goal_fk
    foreign key (goal_id, user_id)
    references public.goals (id, user_id) on delete cascade
);

-- ---------------------------------------------------------------------------
-- habits
-- ---------------------------------------------------------------------------

create table public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  frequency text not null,
  target_per_period integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint habits_name_length check (char_length(btrim(name)) between 1 and 120),
  constraint habits_description_length check (char_length(description) <= 1000),
  -- V1 avoids complex custom schedules — daily or weekly only.
  constraint habits_frequency_allowed check (frequency in ('daily', 'weekly')),
  constraint habits_target_per_period_range check (target_per_period between 1 and 100),
  -- Target for the composite foreign key from habit_checkins.
  constraint habits_id_user_id_key unique (id, user_id)
);

create table public.habit_checkins (
  id bigint generated by default as identity primary key,
  habit_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null,
  value integer not null default 1,
  note text,
  created_at timestamptz not null default now(),
  constraint habit_checkins_value_range check (value between 1 and 1000),
  constraint habit_checkins_note_length check (note is null or char_length(note) <= 500),
  constraint habit_checkins_unique_day unique (habit_id, checkin_date),
  constraint habit_checkins_habit_fk
    foreign key (habit_id, user_id)
    references public.habits (id, user_id) on delete cascade
);

-- ---------------------------------------------------------------------------
-- journal_entries
-- ---------------------------------------------------------------------------

create table public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  body text not null,
  mood text,
  entry_date date not null default current_date,
  -- Optional cross-links. Plain single-column FKs (not composite) so
  -- ON DELETE SET NULL unlinks cleanly without touching user_id. Same-owner
  -- integrity for all three is enforced by the
  -- enforce_journal_entry_ownership() trigger below, not by the FK itself.
  goal_id bigint references public.goals(id) on delete set null,
  habit_id bigint references public.habits(id) on delete set null,
  prime_assignment_id bigint references public.prime_assignments(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint journal_entries_title_length
    check (title is null or char_length(btrim(title)) between 1 and 200),
  constraint journal_entries_body_length
    check (char_length(body) between 1 and 10000),
  -- Moods are self-reported vocabulary for reflection, never a diagnosis.
  constraint journal_entries_mood_allowed check (
    mood is null or mood in (
      'calm', 'focused', 'energised', 'neutral', 'stressed', 'low',
      'grateful', 'reflective'
    )
  )
);

-- ---------------------------------------------------------------------------
-- Indexes (based on the query shapes the application layer actually uses)
-- ---------------------------------------------------------------------------

create index goals_user_status_created_idx
  on public.goals (user_id, status, created_at desc);
create index goal_milestones_goal_position_idx
  on public.goal_milestones (goal_id, position);

create index habits_user_active_idx on public.habits (user_id, is_active);
create index habit_checkins_habit_date_idx
  on public.habit_checkins (habit_id, checkin_date desc);
create index habit_checkins_user_date_idx
  on public.habit_checkins (user_id, checkin_date desc);

create index journal_entries_user_date_idx
  on public.journal_entries (user_id, entry_date desc);

-- ---------------------------------------------------------------------------
-- Triggers: system-managed derived columns
-- ---------------------------------------------------------------------------

create trigger goals_set_updated_at
before update on public.goals
for each row execute function public.set_updated_at();

-- Keeps completed_at / progress_percent consistent with a status change in
-- the same statement: entering 'completed' stamps completed_at and forces
-- progress_percent to 100 (satisfying goals_completed_progress_full without
-- requiring the caller to also send progress_percent); leaving 'completed'
-- (a reopen) clears completed_at. progress_percent is left as-is on reopen —
-- nothing in the brief asks for it to reset, and the owner can call
-- setGoalProgress again once the goal is no longer 'completed'.
create function public.apply_goal_completion_status()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' then
    new.completed_at := now();
    new.progress_percent := 100;
  elsif new.status <> 'completed' and old.status = 'completed' then
    new.completed_at := null;
  end if;
  return new;
end;
$$;

create trigger goals_apply_completion_status
before update on public.goals
for each row execute function public.apply_goal_completion_status();

create trigger habits_set_updated_at
before update on public.habits
for each row execute function public.set_updated_at();

-- Keeps archived_at consistent with is_active in the same statement, the
-- same "derived column excluded from every grant" pattern
-- connections.last_meaningful_contact_at uses (there via an RPC; here via a
-- trigger, since flipping is_active is a plain column update with no other
-- side effect to coordinate).
create function public.apply_habit_archived_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.is_active = false and old.is_active = true then
    new.archived_at := now();
  elsif new.is_active = true and old.is_active = false then
    new.archived_at := null;
  end if;
  return new;
end;
$$;

create trigger habits_apply_archived_at
before update on public.habits
for each row execute function public.apply_habit_archived_at();

create trigger journal_entries_set_updated_at
before update on public.journal_entries
for each row execute function public.set_updated_at();

-- Same-owner integrity for journal_entries' three optional cross-links.
-- security definer so the existence checks are not themselves subject to
-- goals/habits/prime_assignments RLS from inside the trigger — the check is
-- against new.user_id either way, so this only ever confirms what RLS would
-- already imply, never widens what a caller can see.
create function public.enforce_journal_entry_ownership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.goal_id is not null and not exists (
    select 1 from public.goals where id = new.goal_id and user_id = new.user_id
  ) then
    raise exception using errcode = '42501', message = 'That goal is not available.';
  end if;

  if new.habit_id is not null and not exists (
    select 1 from public.habits where id = new.habit_id and user_id = new.user_id
  ) then
    raise exception using errcode = '42501', message = 'That habit is not available.';
  end if;

  if new.prime_assignment_id is not null and not exists (
    select 1 from public.prime_assignments
    where id = new.prime_assignment_id and user_id = new.user_id
  ) then
    raise exception using errcode = '42501', message = 'That Daily Prime is not available.';
  end if;

  return new;
end;
$$;

create trigger journal_entries_enforce_ownership
before insert or update on public.journal_entries
for each row execute function public.enforce_journal_entry_ownership();

revoke all on function public.apply_goal_completion_status() from public, anon, authenticated;
revoke all on function public.apply_habit_archived_at() from public, anon, authenticated;
revoke all on function public.enforce_journal_entry_ownership() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.goals enable row level security;
alter table public.goal_milestones enable row level security;
alter table public.habits enable row level security;
alter table public.habit_checkins enable row level security;
alter table public.journal_entries enable row level security;

revoke all on public.goals from anon, authenticated;
revoke all on public.goal_milestones from anon, authenticated;
revoke all on public.habits from anon, authenticated;
revoke all on public.habit_checkins from anon, authenticated;
revoke all on public.journal_entries from anon, authenticated;

-- goals: owner CRUD, column-scoped INSERT/UPDATE, no DELETE grant at all —
-- goals are archived (status = 'archived'), never hard-deleted. id,
-- created_at, updated_at and completed_at are never client-writable.
grant select on public.goals to authenticated;
grant insert (
  user_id, title, description, category, target_date
) on public.goals to authenticated;
grant update (
  title, description, category, target_date, status, progress_percent
) on public.goals to authenticated;

-- goal_milestones: read-only for clients. Rows are created only by
-- add_goal_milestone() and changed only by toggle_goal_milestone() — no
-- direct INSERT/UPDATE/DELETE grant, matching connection_interactions.
grant select on public.goal_milestones to authenticated;

-- habits: owner CRUD, column-scoped INSERT/UPDATE, no DELETE grant — habits
-- are archived (is_active = false), never hard-deleted. archived_at is
-- trigger-managed and never client-writable.
grant select on public.habits to authenticated;
grant insert (
  user_id, name, description, frequency, target_per_period
) on public.habits to authenticated;
grant update (
  name, description, frequency, target_per_period, is_active
) on public.habits to authenticated;

-- habit_checkins: read-only for clients. Rows are created/updated only by
-- check_in_habit() and removed only by undo_habit_checkin() — matching
-- connection_interactions / goal_milestones.
grant select on public.habit_checkins to authenticated;

-- journal_entries: owner CRUD including DELETE. A journal entry is private,
-- single-owner data with no downstream reference from any other table, so a
-- hard delete (confirmed in the UI) is acceptable here — unlike goals/habits,
-- there is no history-of-record concern (no streak, no milestone count) that
-- a delete would silently corrupt.
grant select, insert (
  user_id, title, body, mood, entry_date, goal_id, habit_id, prime_assignment_id
), update (
  title, body, mood, entry_date, goal_id, habit_id, prime_assignment_id
), delete on public.journal_entries to authenticated;

create policy "Users can read their own goals"
on public.goals for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own goals"
on public.goals for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own goals"
on public.goals for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can read their own goal milestones"
on public.goal_milestones for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their own habits"
on public.habits for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own habits"
on public.habits for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own habits"
on public.habits for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can read their own habit checkins"
on public.habit_checkins for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their own journal entries"
on public.journal_entries for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own journal entries"
on public.journal_entries for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own journal entries"
on public.journal_entries for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own journal entries"
on public.journal_entries for delete
to authenticated
using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------------------
-- RPCs — goal_milestones and habit_checkins are RPC-only for writes
-- ---------------------------------------------------------------------------

-- Appends a milestone to an owned goal at the next position. Position is
-- always server-computed (max(position) + 1) so the browser can never choose
-- or collide a position.
create function public.add_goal_milestone(p_goal_id bigint, p_title text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_title text := btrim(coalesce(p_title, ''));
  v_position integer;
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.goals where id = p_goal_id and user_id = v_viewer
  ) then
    raise exception using errcode = '42501', message = 'This goal is not available.';
  end if;

  if char_length(v_title) < 1 or char_length(v_title) > 200 then
    raise exception using errcode = '22023', message = 'Choose a title between 1 and 200 characters.';
  end if;

  select coalesce(max(position), 0) + 1 into v_position
  from public.goal_milestones
  where goal_id = p_goal_id;

  insert into public.goal_milestones (goal_id, user_id, title, position)
  values (p_goal_id, v_viewer, v_title, v_position)
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- Flips a milestone's completion state. Ownership is resolved through the
-- milestone's own goal_id/user_id pair (identical to how the milestone was
-- created), so a milestone can never be toggled by anyone but the goal owner.
create function public.toggle_goal_milestone(p_milestone_id bigint)
returns table (id bigint, is_completed boolean, completed_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_current boolean;
  v_next boolean;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select m.is_completed into v_current
  from public.goal_milestones m
  where m.id = p_milestone_id and m.user_id = v_viewer;

  if not found then
    raise exception using errcode = '42501', message = 'This milestone is not available.';
  end if;

  v_next := not v_current;

  update public.goal_milestones
  set is_completed = v_next,
      completed_at = case when v_next then now() else null end
  where goal_milestones.id = p_milestone_id;

  return query
  select m.id, m.is_completed, m.completed_at
  from public.goal_milestones m
  where m.id = p_milestone_id;
end;
$$;

-- Records (or updates) today's — or an explicitly dated — check-in for an
-- owned, active habit. Idempotent per (habit_id, checkin_date): calling it
-- again the same day updates value/note rather than erroring, so a user can
-- correct a same-day check-in without an explicit undo first.
create function public.check_in_habit(
  p_habit_id bigint,
  p_checkin_date date default current_date,
  p_value integer default 1,
  p_note text default null
)
returns table (
  id bigint,
  habit_id bigint,
  checkin_date date,
  value integer,
  note text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
  v_note text := nullif(btrim(coalesce(p_note, '')), '');
  v_date date := coalesce(p_checkin_date, current_date);
  v_new_id bigint;
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.habits
    where id = p_habit_id and user_id = v_viewer and is_active
  ) then
    raise exception using errcode = '42501', message = 'This habit is not available.';
  end if;

  if v_date > current_date then
    raise exception using errcode = '22023', message = 'Check-in date cannot be in the future.';
  end if;

  if p_value is null or p_value < 1 or p_value > 1000 then
    raise exception using errcode = '22023', message = 'Choose a value between 1 and 1000.';
  end if;

  if v_note is not null and char_length(v_note) > 500 then
    raise exception using errcode = '22023', message = 'Keep the note to 500 characters or fewer.';
  end if;

  insert into public.habit_checkins (habit_id, user_id, checkin_date, value, note)
  values (p_habit_id, v_viewer, v_date, p_value, v_note)
  on conflict (habit_id, checkin_date) do update
    set value = excluded.value, note = excluded.note
  returning habit_checkins.id into v_new_id;

  return query
  select c.id, c.habit_id, c.checkin_date, c.value, c.note
  from public.habit_checkins c
  where c.id = v_new_id;
end;
$$;

-- Removes a check-in for an owned habit. A no-op (not an error) when no
-- check-in exists for that date — undoing something never checked in is
-- harmless, matching leave_community()'s no-op-for-non-member precedent.
create function public.undo_habit_checkin(
  p_habit_id bigint,
  p_checkin_date date default current_date
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_viewer uuid := auth.uid();
begin
  if v_viewer is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  if not exists (
    select 1 from public.habits where id = p_habit_id and user_id = v_viewer
  ) then
    raise exception using errcode = '42501', message = 'This habit is not available.';
  end if;

  delete from public.habit_checkins
  where habit_id = p_habit_id
    and user_id = v_viewer
    and checkin_date = coalesce(p_checkin_date, current_date);
end;
$$;

revoke all on function public.add_goal_milestone(bigint, text) from public, anon;
revoke all on function public.toggle_goal_milestone(bigint) from public, anon;
revoke all on function public.check_in_habit(bigint, date, integer, text) from public, anon;
revoke all on function public.undo_habit_checkin(bigint, date) from public, anon;

grant execute on function public.add_goal_milestone(bigint, text) to authenticated;
grant execute on function public.toggle_goal_milestone(bigint) to authenticated;
grant execute on function public.check_in_habit(bigint, date, integer, text) to authenticated;
grant execute on function public.undo_habit_checkin(bigint, date) to authenticated;

commit;
